const early = require("./en-01-07.cjs");
const middle = require("./en-08-15.cjs");
const advanced = require("./en-16-17.cjs");

const old = [...early, ...middle, ...advanced];
const copy = value => structuredClone(value);
const revise = (source, n, overrides) => ({ ...copy(source), ...overrides, n });

const day7 = {
  n: 7,
  t: "LLM Foundations",
  s: "Map the origins, historical path, mechanics, and essential terminology of language models",
  goal: "Understand the path from statistical and neural language models to Transformers, pretraining, and instruction alignment, and accurately explain tokens, parameters, context, pretraining, inference, and hallucination.",
  concept: ["Language modeling and next-token prediction", "Tokens, embeddings, parameters, and context windows", "Pretraining, fine-tuning, instruction alignment, and inference", "Scaling, emergent capabilities, and foundation models", "Probabilistic generation, hallucination, and capability boundaries"],
  analogy: "Treat an LLM as a probabilistic protocol stack trained on vast text: tokens are frame units, parameters are frozen statistical state, context is the current session buffer, and inference predicts the next likely unit one step at a time.",
  diagram: "Text corpus ──tokenize──► token sequences ──pretrain: predict next token──► base model\nUser instruction ──template──► context ──token-by-token inference──► distribution ──sample──► output",
  code: "tokens = tokenizer(chat_template(messages))\nfor token in tokens:\n    state = model(token, state)\nwhile not stop:\n    logits, state = model(next_token, state)\n    next_token = sample(logits)",
  lab: "Choose one mixed Chinese-English prompt. Record its character count, then obtain its token count with an open tokenizer. Generate three times with the same model at temperature=0 and at a higher temperature, recording output differences. Finally draw the five-stage corpus→pretraining→base model→instruction alignment→inference chain and label every stage's input, output, and non-guarantees.",
  questions: ["Why can next-token prediction learn transferable language and knowledge patterns?", "How do parameters, the context window, and KV cache differ in state type and lifetime?", "What does instruction alignment improve, and why can it not eliminate hallucinations?"],
  next: "Tokenizer",
  lesson: [
    { title: "Start from the task definition: an LLM is a conditional probability model", body: "A language model learns a probability distribution for the next token conditioned on the visible prefix. During training, shifting a real sequence by one position creates supervision at every position; during inference, one selected token is appended before predicting again. This objective pressures the model to compress syntax, semantics, factual co-occurrence, and task formats. It optimizes predictive likelihood, however—not database consistency, complete logical proof, or real-world safety." },
    { title: "From statistical counts to distributed representations, the recurring problem is generalization", body: "Early n-gram models counted the next word after a finite history. They were simple and interpretable but suffered from unseen combinations and dimensional explosion. Neural language models mapped discrete words into continuous embeddings and shared parameters across similar contexts. Methods such as word2vec made the reuse of distributed representations especially visible. LLMs are not a sudden magic trick; they join decades of language objectives, representation learning, compute scaling, and data engineering." },
    { title: "Transformers made long dependencies and large-scale parallel training more practical", body: "Recurrent networks pass state through a sequence one step at a time, creating long paths for both parallel execution and distant credit assignment. Transformers use self-attention for direct position-to-position interaction, then add position-wise feed-forward networks, residual paths, normalization, and positional mechanisms. Training can process a full sequence in parallel, but autoregressive output still has order. Input processing and output generation are distinct workloads explored later through Attention, Prefill, Decode, and KV cache." },
    { title: "Pretraining, fine-tuning, and alignment have different responsibilities", body: "Pretraining learns general representations and generation behavior from broad corpora. Supervised fine-tuning shapes a narrower task and response format. Instruction alignment uses demonstrations, preferences, or rules to make behavior more useful and safer. All can change weights, but their data, objectives, and acceptance criteria differ. In-context learning is different again: examples in a prompt affect only the current context and do not permanently update parameters. Calling every process “training” obscures cost, privacy, rollback, and ownership." },
    { title: "Scale brings capabilities while amplifying data, evaluation, and system problems", body: "Parameter count, training data, and compute jointly affect capacity, and no single number is a universal capability score. Larger models may show stronger few-shot transfer and task generalization, but demand more training resources, weight storage, inference bandwidth, and data governance. A foundation model is a pretrained base adaptable to many tasks, not a certification that it understands everything. Comparisons must fix the workload, prompt template, context, precision, hardware, and evaluation set." },
    { title: "Place common terms in the correct lifecycle", body: "A token is a discrete identifier defined by a tokenizer; an embedding is its vector representation; parameters are long-lived trained state reused across requests; context is the token sequence visible to one request; KV cache is temporary per-layer state produced from that sequence; logits are unnormalized next-token scores; and sampling chooses the emitted token. Once these lifetimes are explicit, the model file, session memory, serving scheduler, and user experience can share one resource ledger." },
    { title: "Fluent probability is not factual reliability", body: "A model continues text according to its training distribution and current context, so it can produce grammatical but false, fabricated, or contradictory claims. Retrieval, tools, structured constraints, and human review reduce risk without automatically turning a probabilistic model into a source of truth. An edge product must define where the model may advise, keep actuation, safety decisions, and irreversible actions behind deterministic checks, and continuously evaluate real failure examples." },
  ],
  pitfall: "Treating parameter count as an intelligence scale or fluent prose as verified fact. Capability depends on data, objectives, prompts, context, and evaluation; generated content must pass deterministic checks before it becomes a device action.",
  references: [["Original neural probabilistic language-model paper", "https://www.jmlr.org/papers/v3/bengio03a.html"], ["Original Attention Is All You Need paper", "https://arxiv.org/abs/1706.03762"], ["Original GPT-3 paper", "https://arxiv.org/abs/2005.14165"]],
  quiz: [
    { prompt: "What is the most typical self-supervised objective for autoregressive LLM pretraining?", options: ["Memorize every document filename", "Predict the next token from visible tokens", "Compress every sentence into one identical vector", "Directly verify real-world facts"], answer: 1, explanation: "Autoregressive language models predict the next token from a prefix, allowing ordinary unlabeled text to provide supervision at many positions." },
    { prompt: "Which statement best distinguishes parameters from context?", options: ["Both update permanently after every token", "Parameters are reused across requests; context is the sequence visible to one request", "Context is stored inside the model weights file", "Parameters are the tokenizer vocabulary"], answer: 1, explanation: "Parameters are trained model state reused during inference; context is the token sequence belonging to a request or session." },
    { prompt: "Why can an instruction-aligned model still hallucinate?", options: ["Alignment deletes the tokenizer", "Generation remains conditional probability prediction, so alignment cannot prove every statement true", "KV cache must always be corrupted", "Every model can process only English"], answer: 1, explanation: "Alignment improves behavior and preferences but does not turn probabilistic generation into factual proof; important output still needs external evidence." },
  ],
  readingMinutes: 20,
  keywords: [
    { term: "Language model", definition: "A model that estimates sequence probability or the conditional probability of the next token.", espAnalogy: "Like predicting the next protocol field's type and range from fields already received." },
    { term: "Parameter", definition: "A trained weight reused unchanged during inference—the model's long-lived statistical state.", espAnalogy: "Like lookup constants and control coefficients compiled into firmware and reused across requests." },
    { term: "Pretraining / alignment", definition: "Pretraining learns broad patterns; alignment uses instructions, preferences, or rules to shape usable behavior.", espAnalogy: "Like building a general parser, then constraining commands and error handling to a product specification." },
    { term: "Hallucination", definition: "Fluent model output that lacks factual support or conflicts with reality.", espAnalogy: "Like a checksum-valid, well-formed packet whose payload semantics are still wrong." },
  ],
  recap: "The first six days established the conventional AI engineering loop from neural networks and model artifacts to constrained edge deployment and vision pipelines. Today crosses into generative language models by building a map that is not distorted by tool names or parameter counts.",
  nextPreview: "Next, Tokenizer traces text into token IDs and treats the vocabulary, special tokens, and chat template as a model ABI.",
  history: {
    intro: "LLMs did not arrive in one paper. Probabilistic language modeling, distributed representations, parallel architectures, scaled pretraining, and human-preference alignment accumulated over decades. Their milestones reveal which capabilities come from objectives, structures, and deployment systems.",
    milestones: [
      { year: "1948", title: "Information theory measures language uncertainty and predictability", body: "Shannon used entropy and conditional probability to study communication and English sequences, establishing a starting point for treating language as a stochastic process whose uncertainty falls with context.", source: { label: "Original Shannon paper", url: "https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf" } },
      { year: "2003", title: "A neural probabilistic language model learns distributed word representations", body: "Bengio and collaborators estimated next-word probabilities with shared continuous word vectors and a neural network, letting related contexts share statistical strength and reducing the n-gram curse of dimensionality.", source: { label: "Original neural language-model paper", url: "https://www.jmlr.org/papers/v3/bengio03a.html" } },
      { year: "2017", title: "The Transformer rebuilds sequence modeling around Attention", body: "Attention Is All You Need removed recurrent and convolutional backbones, organizing self-attention, feed-forward layers, residual paths, and positional encodings into a parallelizable encoder-decoder.", source: { label: "Original Transformer paper", url: "https://arxiv.org/abs/1706.03762" } },
      { year: "2018", title: "BERT shows that broad pretraining can transfer to many understanding tasks", body: "Bidirectional Transformer pretraining followed by task fine-tuning demonstrated a reusable base representation that could adapt to many natural-language understanding workloads.", source: { label: "Original BERT paper", url: "https://arxiv.org/abs/1810.04805" } },
      { year: "2020", title: "GPT-3 demonstrates in-context learning in a scaled autoregressive model", body: "GPT-3 performed varied tasks from instructions or a few prompt examples without parameter updates, making scale, prompt design, and in-context learning central research and product variables.", source: { label: "Original GPT-3 paper", url: "https://arxiv.org/abs/2005.14165" } },
      { year: "2022", title: "InstructGPT adds instruction following and human preference to the alignment chain", body: "Supervised demonstrations, a reward model, and reinforcement learning from human feedback were combined to make a base model more likely to follow user intent while exposing the importance of alignment evaluation and safety boundaries.", source: { label: "Original InstructGPT paper", url: "https://arxiv.org/abs/2203.02155" } },
    ],
    bridge: "Local and edge LLMs still follow this chain: a tokenizer defines inputs, Transformer weights carry pretraining and alignment, and a runtime manages context and token generation. Device optimization changes representation, state, and movement—not what the model never learned or cannot guarantee.",
  },
  visual: {
    title: "How language capability travels from a corpus into one answer",
    description: "The player separates long-lived training from short-lived request inference so parameters, context, and cache do not collapse into one vague state.",
    steps: [
      { icon: "📚", label: "Curate the corpus", data: "documents + provenance", action: "Clean, deduplicate, filter, and record sources", insight: "Both capability and risk begin in the data distribution" },
      { icon: "🔤", label: "Create tokens", data: "text → token ids", action: "Encode with fixed normalization and vocabulary rules", insight: "Character count is not model sequence length" },
      { icon: "🏋️", label: "Pretrain", data: "prefix → next token", action: "Compute loss repeatedly and update parameters", insight: "Broad patterns enter weights reused across requests" },
      { icon: "🧭", label: "Align instructions", data: "instruction + preference", action: "Shape response format, helpfulness, and safety behavior", insight: "Better behavior is not a factual guarantee" },
      { icon: "💬", label: "Construct context", data: "system + history + user", action: "Apply the template and form the visible prefix", insight: "Context belongs only to this session" },
      { icon: "✨", label: "Generate token by token", data: "logits → sample → append", action: "Predict, select, append, and repeat", insight: "Every emitted token becomes the next step's input" },
    ],
    loop: "Generation loops at “Generate token by token” until EOS, a limit, or cancellation; only offline training or fine-tuning returns to parameter updates.",
  },
  analogyDetail: {
    title: "A repeatedly revised but read-only-on-site protocol predictor",
    story: "A lab trains predictor firmware from a large archive of packets and compresses recurring structure into parameters. A product team then calibrates how it responds to commands. For a live request, the device loads fixed firmware, places the current packet in a session buffer, and predicts subsequent parts. The output may be smooth, but critical fields still pass deterministic validation.",
    illustration: [
      { icon: "📦", label: "Historical packet archive", mapsTo: "Pretraining corpus and data governance" },
      { icon: "💾", label: "Predictor firmware", mapsTo: "Frozen model parameters reused across requests" },
      { icon: "🧾", label: "Current packet buffer", mapsTo: "The request's token context" },
      { icon: "✅", label: "Protocol validator", mapsTo: "Tools, rules, retrieval, and human-review boundaries" },
    ],
    boundary: "LLM parameters are not a database of individually queryable facts, and tokens are not fixed semantic protocol fields. The analogy distinguishes training-time state, request-time state, and external validation responsibility.",
  },
};

const day9 = {
  n: 9,
  t: "Transformer Architecture",
  s: "Understand the whole model before opening its Attention dataflow",
  goal: "Understand how a Transformer organizes embeddings, positions, Attention, FFNs, residual connections, and normalization into encoder, decoder, and decoder-only architectures, then reconstruct the complete token-to-logits path from a model configuration.",
  concept: ["Encoder, decoder, and decoder-only", "Embeddings, positions, and output heads", "Transformer blocks and layer stacks", "Residuals, normalization, and FFNs", "Parallel training and sequential generation"],
  analogy: "Like reading a complete SoC block diagram first: interfaces, interconnect, compute units, bypasses, and output control each own a responsibility. Attention is the interconnect core, but it is not the architecture of the entire chip.",
  diagram: "token ids → embedding + position → N × Transformer block → final norm → logits\n                                     │\n                 Attention → residual → FFN → residual",
  code: "x = token_embedding(token_ids) + position(position_ids)\nfor block in transformer_blocks:\n    x = block(x, mask=causal_mask)\nlogits = output_head(final_norm(x))",
  lab: "Choose an open decoder-only model and inspect its configuration and printed module tree. Record vocabulary size, hidden size, layer count, attention heads, KV heads, FFN intermediate size, positional mechanism, and whether input and output embeddings are tied. Draw the tensor shapes through one block, estimate the embedding, Attention, and FFN parameter shares, and verify the logits shape for a short sequence.",
  questions: ["How do encoder, encoder–decoder, and decoder-only architectures differ in visibility and output objective?", "Why does a block need position-wise FFNs, residual paths, and normalization in addition to Attention?", "Why can known training positions move through a layer in parallel while autoregressive generation still advances token by token?"],
  next: "Attention Mechanisms",
  lesson: [
    { title: "Treat the Transformer as an architecture, not one formula", body: "A Transformer is a framework for organizing sequence computation. Tokens enter embeddings and a positional mechanism, pass through a stack of repeated blocks, and reach final normalization and an output head that produces logits. A block usually contains Attention for cross-position exchange, an FFN for position-wise transformation, and residual and normalization paths that preserve deep signals. Fixing those boundaries first prevents one Attention formula from standing in for the whole model." },
    { title: "Encoders, decoders, and decoder-only models carry different information flows", body: "An encoder lets every position read the full input and is suited to contextual representations. The original decoder combines causal self-attention over its generated prefix with cross-attention to encoder output. A decoder-only model places instructions, context, and answers in one causal sequence and applies one next-token objective. The families share the block idea but differ in masks, input contracts, and objectives, so the Transformer label alone does not make them interchangeable." },
    { title: "Embeddings, positions, and the output head define both ends of the sequence", body: "A token ID is only a discrete index; an input embedding maps it into a hidden vector, and a positional encoding or rotary mechanism makes order and distance available. After the layer stack, hidden states pass through a final normalization and vocabulary projection to become logits. Some models tie that projection to the input embedding. Vocabulary size, hidden width, position parameters, and weight tying all change file size, operator shapes, and compatibility, so they belong in the model-package contract." },
    { title: "The FFN is the main nonlinear path at each position", body: "Attention mixes information across positions, while an FFN independently applies the same expansion, activation, and contraction parameters at every position. The classic Transformer used a two-layer feed-forward network; modern LLMs often use gated MLP variants. Intermediate width and activation choice materially affect parameter count, memory traffic, and kernel coverage. Account for Attention projections and FFN weights separately instead of attributing all block cost to Attention." },
    { title: "Residuals and normalization govern stable deep propagation", body: "Residual connections give each sublayer a short path that preserves and revises the existing representation, while LayerNorm or RMSNorm controls numerical scale. Models may use pre-norm, post-norm, parallel residuals, or different normalization formulas, and conversion cannot reorder them casually. Save golden tensors at block boundaries when validating a backend so the first error can be assigned to normalization, residual addition, or the sublayer computation." },
    { title: "Training parallelism and generation order live on different axes", body: "During training the complete target sequence is known, so a causal mask can block future information while positions in one layer are computed as a batch; layers still follow graph dependencies. During generation, the next token does not exist until current logits have been sampled. The Transformer shortens paths among positions and improves training parallelism, but does not remove autoregressive time dependence. That distinction motivates the next Attention and KV-cache chapters." },
  ],
  pitfall: "Equating the Transformer with Attention, or treating parallelizable as permission to run layers and generation steps in arbitrary order. The full architecture includes embeddings, positions, FFNs, residuals, normalization, and an output head; every parallelism claim must name its batch, position, head, tensor, or pipeline axis.",
  references: [["Original Attention Is All You Need paper", "https://arxiv.org/abs/1706.03762"], ["Original BERT paper", "https://arxiv.org/abs/1810.04805"], ["Original GPT-3 paper", "https://arxiv.org/abs/2005.14165"]],
  quiz: [
    { prompt: "What is the primary role of the FFN inside a Transformer block?", options: ["Apply a shared nonlinear representation transform at every position", "Choose how the tokenizer segments text", "Permanently store every session's KV", "Replace the residual connection"], answer: 0, explanation: "Attention exchanges information across positions; the FFN independently applies the same nonlinear parameterized transform at each position." },
    { prompt: "What visibility constraint is most typical for a decoder-only LLM?", options: ["Every position reads future answers", "Every position reads only itself", "Every position reads the current and earlier tokens", "Every position reads only image patches"], answer: 2, explanation: "Causal visibility lets a position use its prefix while preventing future training labels from leaking into the computation." },
    { prompt: "Which statement best describes Transformer training parallelism and generation order?", options: ["Neither training nor generation has order dependencies", "Known training positions can run in parallel, but a generated token still depends on the previous step", "Only the FFN can be trained", "The layer stack may execute backward"], answer: 1, explanation: "Training sees the full sequence and uses a mask to preserve causality; generation must wait until the preceding token has been selected." },
  ],
  readingMinutes: 20,
  keywords: [
    { term: "Transformer block", definition: "A repeated sequence unit composed of sublayers such as Attention, an FFN, residual paths, and normalization.", espAnalogy: "Like a repeated SoC compute tile containing both an interconnect and a local processing path." },
    { term: "Decoder-only", definition: "A stack of decoder-style blocks with causal visibility, trained to generate the next token from one unified sequence.", espAnalogy: "Like a state machine that advances only from the protocol prefix already received." },
    { term: "FFN / MLP", definition: "A nonlinear feed-forward sublayer applied independently at each sequence position with shared parameters.", espAnalogy: "Like every packet passing through the same local field-transform unit." },
    { term: "Residual + Norm", definition: "Short paths that preserve representations together with controls on numerical scale through deep stacks.", espAnalogy: "Like a main-data bypass and level calibration keeping a long pipeline stable." },
  ],
  recap: "Day 7 established the LLM history and vocabulary map, and Day 8 fixed the text-input ABI. This chapter treats the Transformer as its own architectural concept and traces the whole path from tokens and blocks to logits.",
  nextPreview: "Day 10 gives Attention its own chapter, moving from learned alignment, Q/K/V, and causal masks to multi-head computation, quadratic cost, and I/O-aware implementations.",
  history: {
    intro: "Transformer history is not the expansion of one Attention formula. Its architectural skeleton, pretraining objectives, positional mechanisms, and scaling methods evolved together. Different branches retain related blocks while choosing distinct information flows for understanding, generation, and long-context tasks.",
    milestones: [
      { year: "2017", title: "The Transformer establishes a recurrence-free encoder–decoder skeleton", body: "The original paper assembled multi-head Attention, position-wise FFNs, residuals, LayerNorm, and positional encoding into stackable blocks, allowing high parallelism across sequence positions during training.", source: { label: "Original Transformer paper", url: "https://arxiv.org/abs/1706.03762" } },
      { year: "2018", title: "GPT validates transfer after generative decoder pretraining", body: "Generative pretraining applied a multilayer Transformer decoder to general language modeling before task fine-tuning, establishing an important starting point for the decoder-only route.", source: { label: "Original GPT paper", url: "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf" } },
      { year: "2018", title: "BERT strengthens bidirectional encoder pretraining", body: "BERT used masked language modeling to incorporate context from both directions, demonstrating that an encoder-only Transformer could produce transferable language representations.", source: { label: "Original BERT paper", url: "https://arxiv.org/abs/1810.04805" } },
      { year: "2019", title: "Transformer-XL extends dependencies across segments", body: "Segment-level hidden-state recurrence and relative positional encoding preserved longer history beyond fixed training segments while making the boundaries of state reuse explicit.", source: { label: "Original Transformer-XL paper", url: "https://arxiv.org/abs/1901.02860" } },
      { year: "2020", title: "GPT-3 demonstrates in-context learning at decoder-only scale", body: "GPT-3 scaled an autoregressive Transformer and completed tasks from descriptions and examples in its prompt, bringing decoder-only scaling and in-context learning into the main line.", source: { label: "Original GPT-3 paper", url: "https://arxiv.org/abs/2005.14165" } },
      { year: "2021", title: "Switch Transformer explores sparse expert FFNs", body: "Sparse routing activated only selected expert FFNs for each token, increasing conditional parameter capacity while adding routing, load-balancing, and communication costs to the architecture.", source: { label: "Original Switch Transformer paper", url: "https://arxiv.org/abs/2101.03961" } },
    ],
    bridge: "An edge deployment should first recover the Transformer family, block sublayers, positions, and output contract from configuration and graph evidence. Only then can Attention, FFNs, KV state, and backends be optimized separately.",
  },
  visual: {
    title: "How a token sequence crosses a complete Transformer",
    description: "The player shows the model-level path and intentionally leaves Attention as one sublayer to be opened in the next chapter.",
    steps: [
      { icon: "🔢", label: "Receive token IDs", data: "[batch, sequence]", action: "Read the tokenizer's discrete indices", insight: "Vocabulary and embedding weights must match" },
      { icon: "🧭", label: "Add position", data: "token vector + position", action: "Establish content representations and order", insight: "The position mechanism belongs to model configuration" },
      { icon: "🔀", label: "Exchange across positions", data: "Attention sublayer", action: "Read context permitted for every position", insight: "Day 10 opens the internal Q/K/V path" },
      { icon: "🧱", label: "Residual and norm", data: "skip + normalize", action: "Merge sublayer results and stabilize scale", insight: "Conversion cannot reorder this path casually" },
      { icon: "⚙️", label: "Apply the FFN", data: "hidden → intermediate → hidden", action: "Run the shared nonlinear transform per position", insight: "FFNs often consume substantial weights and bandwidth" },
      { icon: "📊", label: "Project to logits", data: "hidden → vocabulary", action: "Produce next-token scores with the output head", insight: "A logit vector is not yet a selected token" },
    ],
    loop: "Attention, residual, normalization, and FFN paths repeat for N configured layers. After sampling, each new autoregressive position crosses the complete stack again.",
  },
  analogyDetail: {
    title: "Read the SoC block diagram before opening the interconnect",
    story: "Input indices pass through an interface and address marker, then cross repeated compute tiles. Each tile contains an interconnect for exchanging information, local nonlinear processing, bypasses, and level calibration. The output unit maps internal state to vocabulary scores. Studying only the interconnect would miss most weights, execution order, and compatibility contracts.",
    illustration: [
      { icon: "🧭", label: "Input interface and address", mapsTo: "Token embeddings and positional mechanism" },
      { icon: "🔀", label: "On-chip interconnect", mapsTo: "Cross-position communication in Attention" },
      { icon: "⚙️", label: "Local compute tile", mapsTo: "Position-wise FFN / MLP" },
      { icon: "📊", label: "Output encoder", mapsTo: "Final norm, output head, and logits" },
    ],
    boundary: "A Transformer is not a physical SoC, and layers need not map to separate hardware units. The analogy only separates whole-model architecture, repeated blocks, cross-position exchange, and local computation.",
  },
};

const day10 = revise(old[9], 10, {
  t: "Attention Mechanisms",
  s: "Turn sequence dependencies into an explicit, parallelizable dataflow",
  goal: "Start from Attention's alignment problem, understand scaled dot products, Query, Key, Value, multiple heads, causal masks, and positional interaction, then explain its parallel advantage, quadratic cost, and I/O boundary.",
  concept: ["Query, Key, Value, and scaled dot products", "Self-attention, cross-attention, and multiple heads", "Causal masks and positional encoding", "Residual paths, LayerNorm, and feed-forward networks", "Parallel paths, O(n²), and I/O cost"],
  analogy: "Think of a programmable switching matrix: every position emits a query, matches indexes at all visible positions, retrieves weighted data, and repeats this through several parallel matching channels.",
  diagram: "token ids → embedding + position\n                 │\nQ = XWq, K = XWk, V = XWv\n                 │\nscores = QKᵀ/√dₖ + mask → softmax → weighted V\n                 │\n          residual + norm → FFN → residual + norm",
  code: "scores = Q @ K.T / sqrt(d_k)\nscores = scores + causal_mask\nweights = softmax(scores, axis=-1)\ncontext = weights @ V\noutput = concat(heads) @ W_o",
  lab: "Read the abstract, Sections 3.1–3.5, and Section 4 of Attention Is All You Need. Hand-calculate and implement softmax(QKᵀ/√d_k)V for four tokens with two-dimensional vectors. Toggle the causal mask and verify that position i cannot depend on future positions. Then double sequence length from 4 to 8 and 16 and record the attention-score matrix growth.",
  questions: ["Why divide dot products by √d_k?", "What representational freedom do multiple heads add?", "Why can Transformer training parallelize while autoregressive generation still has order?"],
  next: "KV Cache",
  lesson: old[9].lesson.slice(0, 4).concat([
    { title: "A Transformer block contains more than Attention", body: "Attention exchanges information among positions, while a position-wise feed-forward network applies the same nonlinear transform at every position. Residual connections preserve short paths through a deep model, and LayerNorm stabilizes numerical scales. Engineering analysis should budget QKV projection, score computation, value aggregation, output projection, and the FFN separately. FFN weights often hold a large parameter share, while long contexts make attention intermediates and K/V state major memory and bandwidth consumers." },
    { title: "Self-attention gains short paths and parallelism, not free computation", body: "The paper compares layers by complexity, required sequential operations, and maximum path length between positions. Self-attention shortens distant-dependency paths and processes training positions in parallel, but builds a correlation matrix that grows quadratically with sequence length. Long contexts therefore motivate sparse patterns, tiling, windows, or I/O-aware kernels. Those techniques alter computation, visibility, or data movement in distinct ways and should not be grouped as one generic acceleration." },
    { title: "Check masks, positions, and numerical stability from formula to implementation", body: "Implementation bugs hide in broadcast mask direction, interactions between padding and causal masks, position offsets, softmax dtypes, and multi-head reshape order. Create tiny golden matrices: freeze Q/K/V and save raw scores, scaled scores, masked scores, softmax weights, and final outputs. Verify that every row sums to one and future weights are zero. This baseline exposes the first semantic break when kernels, quantization, or cache management are optimized later." },
  ]),
  pitfall: "Treating Attention as a human-readable explanation of what the model considers important, or mistaking training parallelism for dependency-free generation. Attention is learned weighted dataflow governed by weights, positions, masks, and inputs, and full long-sequence attention still has quadratic cost.",
  references: [["Original Attention Is All You Need paper", "https://arxiv.org/abs/1706.03762"], ["Original BERT paper", "https://arxiv.org/abs/1810.04805"], ["Original FlashAttention paper", "https://arxiv.org/abs/2205.14135"]],
  quiz: [old[9].quiz[0], { prompt: "What does a causal mask guarantee in decoder self-attention?", options: ["All heads share parameters", "The current position cannot read future tokens", "Sequence length is fixed at 512", "Padding tokens are deleted automatically"], answer: 1, explanation: "A causal mask hides future positions, preserving autoregressive semantics even when training positions are computed in parallel." }, { prompt: "If sequence length doubles, how does the full attention-score matrix size change approximately?", options: ["It stays constant", "It becomes four times larger", "It doubles", "It halves"], answer: 1, explanation: "The score matrix is generally n×n; moving from n to 2n changes n² elements into 4n²." }],
  readingMinutes: 20,
  keywords: [
    { term: "Attention", definition: "Information exchange that matches Query against Key and uses the scores to aggregate Value.", espAnalogy: "Like one query searching several indexed DMA descriptors at once." },
    { term: "Multi-head", definition: "Attention projected into several subspaces, run in parallel, and concatenated at the output.", espAnalogy: "Like parallel filters observing different protocol features." },
    { term: "Causal mask", definition: "An upper-triangular visibility constraint that prevents reading future tokens.", espAnalogy: "Like a receiver state machine that can read only bytes already received." },
    { term: "Positional encoding", definition: "Information about token order or relative distance injected into a non-recurrent attention model.", espAnalogy: "Like attaching a monotonic sequence number to each ring-buffer element." },
  ],
  recap: "The previous chapter established the complete Transformer architecture and located Attention as the block sublayer responsible for cross-position communication. This chapter opens that large concept on its own and traces how Q, K, V, masks, heads, and positions determine aggregation.",
  nextPreview: "Next comes KV Cache alone: why historical K/V is reusable, how many bytes every token adds, and how GQA, paging, and quantization alter capacity and bandwidth.",
  history: {
    intro: "Attention began as an answer to fixed-vector compression in encoder-decoder models, became the Transformer dataflow, and later expanded through bidirectional pretraining, other modalities, and I/O-aware kernels. Structure and systems optimization jointly determine practical context length.",
    milestones: [
      { year: "2014", title: "Learned alignment relieves fixed-length encoding pressure", body: "Bahdanau and collaborators let each decoder step calculate alignment weights over encoder states instead of forcing one vector to carry an entire sentence.", source: { label: "Original neural-translation Attention paper", url: "https://arxiv.org/abs/1409.0473" } },
      { year: "2017", title: "The Transformer replaces recurrence with multi-head Attention", body: "Scaled dot products, multi-head self-attention, positional encodings, and causal masks were organized into an encoder-decoder that could train in parallel.", source: { label: "Original Transformer paper", url: "https://arxiv.org/abs/1706.03762" } },
      { year: "2018", title: "BERT builds general language representations with bidirectional self-attention", body: "Masked language modeling used both left and right context, demonstrating that pretrained Transformer encoders transfer across varied understanding tasks.", source: { label: "Original BERT paper", url: "https://arxiv.org/abs/1810.04805" } },
      { year: "2019", title: "Transformer-XL adds segment recurrence and relative position", body: "Reusing hidden state across segments and adopting relative positions let language models capture dependencies beyond fixed training fragments.", source: { label: "Original Transformer-XL paper", url: "https://arxiv.org/abs/1901.02860" } },
      { year: "2020", title: "Vision Transformer carries a pure Transformer backbone into images", body: "Images were divided into patch sequences and processed directly by a Transformer, showing that attention-based position interaction was not limited to natural language.", source: { label: "Original Vision Transformer paper", url: "https://arxiv.org/abs/2010.11929" } },
      { year: "2022", title: "FlashAttention locates the bottleneck in HBM data movement", body: "I/O-aware tiling reduced HBM traffic without approximating attention outputs, proving that the same formula can behave very differently under another memory schedule.", source: { label: "Original FlashAttention paper", url: "https://arxiv.org/abs/2205.14135" } },
    ],
    bridge: "Edge implementations must preserve Q/K/V, masks, and position semantics while facing quadratic sequence work and memory hierarchy. Establish a tiny correctness baseline before selecting fusion, tiling, low precision, or a hardware backend.",
  },
  visual: {
    title: "How one token reads context through multi-head self-attention",
    description: "The player exposes projection, scoring, masking, normalization, aggregation, and block output instead of hiding Attention behind one box.",
    steps: [
      { icon: "🔢", label: "Embed positions", data: "X = token embedding + position", action: "Create an ordered representation at every position", insight: "Attention does not create order by itself" },
      { icon: "🔀", label: "Project Q/K/V", data: "XWq, XWk, XWv", action: "Reshape into several head subspaces", insight: "One input serves as query, index, and value" },
      { icon: "📐", label: "Calculate scaled scores", data: "QKᵀ / √dₖ", action: "Match every query against visible keys", insight: "Scaling keeps large dot products from saturating softmax" },
      { icon: "🚧", label: "Apply visibility", data: "scores + causal/padding mask", action: "Hide future positions and invalid padding", insight: "A mask is model semantics, not merely an optimization hint" },
      { icon: "⚖️", label: "Normalize and read V", data: "softmax(scores) @ V", action: "Aggregate visible values by their weights", insight: "Every weight row should form a probability distribution" },
      { icon: "🧩", label: "Join the block", data: "concat(heads)Wₒ → residual → FFN", action: "Combine heads and continue nonlinear processing", insight: "Attention is only part of a complete Transformer block" },
    ],
    loop: "Every Transformer block repeats this path. Training positions can run in parallel, but a new generated position still waits for the previous token selection.",
  },
  analogyDetail: {
    title: "A parallel, multi-channel retrieval switching matrix",
    story: "Every input port emits a query. Several matching circuits score visible ports using different clues, then retrieve data from corresponding channels. The channel outputs join before local processing. The matrix can serve a complete input batch at once, but it cannot process a next input that has not yet been generated.",
    illustration: [
      { icon: "❓", label: "Query descriptor", mapsTo: "Query: what the current position seeks" },
      { icon: "🏷️", label: "Port index", mapsTo: "Key: how each position can be matched" },
      { icon: "📦", label: "Port payload", mapsTo: "Value: information retrieved after a match" },
      { icon: "📡", label: "Parallel matching channels", mapsTo: "Multiple attention-head subspaces" },
    ],
    boundary: "Heads are not necessarily human-nameable grammar or fact modules, and attention scores alone are not causal explanations. The analogy describes dataflow and parallel structure only.",
  },
});

const day11 = revise(old[9], 11, {
  t: "KV Cache",
  s: "Trade session memory for reuse of historical projections during Decode",
  goal: "Understand the workload split between Prefill and Decode, why K/V can be cached, cache layout and capacity slopes, and the distinct effects of MHA, GQA, MQA, paging, windows, and low precision.",
  concept: ["Prefill and autoregressive Decode", "The mathematical reason K/V can be reused", "Cache shape, lifetime, and position", "GQA/MQA and low-precision KV", "Paged KV, sliding windows, reuse, and reclamation"],
  analogy: "Like preserving layered indexes for packet history already parsed: a new field avoids rebuilding old indexes but still scans visible entries and allocates new state.",
  diagram: "Prompt tokens ──Prefill──► per-layer K/V cache\nNew token ──Q,K,V──► Q × cached Kᵀ → weighted V → logits → sample\n                         └──── append new K/V and repeat ────┘",
  code: "kv_bytes = batch * layers * 2 * tokens * kv_heads * head_dim * bytes_per_value\nbytes_per_new_token = batch * layers * 2 * kv_heads * head_dim * bytes_per_value\n# Also budget alignment, page metadata, and preallocation policy",
  lab: "For a real model, obtain layers, kv_heads, head_dim, and cache dtype. Calculate bytes added per token, then estimate 512, 2,048, and 4,096 tokens. Run a local runtime at several context sizes and record memory, prefill time, and per-token latency. If GQA/MQA or KV quantization is configurable, compare capacity slopes and output quality.",
  questions: ["Why can old-token K/V be reused while Q is usually not retained?", "Why does KV capacity usually grow approximately linearly with context?", "What distinct problems do paging, GQA, and sliding windows solve?"],
  next: "LLM Quantization and GGUF",
  lesson: old[9].lesson.slice(4).concat([
    { title: "Budget Prefill and Decode separately", body: "Prefill processes all prompt tokens in a batch and usually has higher parallelism and compute density. Decode creates only one position per round while repeatedly reading growing historical K/V, so memory bandwidth and scheduling overhead often dominate. TTFT includes queuing, tokenization, prefill, and first-token sampling; ITL measures subsequent token intervals. One average tokens/s number conceals different bottlenecks for long prompts, short answers, and concurrent sessions." },
    { title: "Cache correctness depends on model, prefix, position, and precision", body: "K/V tensors are produced by specific layer weights, a specific token prefix, positional semantics, and cache dtype. Changing the model or adapter, editing the middle of a prefix, shifting positions, or using incompatible rotary parameters normally invalidates old state. A prompt-cache key must cover those identities. Cancellation, timeout, and eviction must return every page or slot, or a long-running service develops a hidden capacity leak." },
  ]),
  pitfall: "Estimating RAM from the weights file alone, or calling paging, windows, and GQA all “KV compression.” They address fragmentation, visible history, and state width respectively, with different capacity, semantic, and quality consequences.",
  references: [["Original GQA paper", "https://arxiv.org/abs/2305.13245"], ["Original vLLM / PagedAttention paper", "https://arxiv.org/abs/2309.06180"], ["Original KIVI KV-cache quantization paper", "https://arxiv.org/abs/2402.02750"]],
  quiz: old[9].quiz.slice(1).concat([{ prompt: "What does PagedAttention improve most directly?", options: ["It writes parameters into the tokenizer", "Allocation, fragmentation, and sharing of dynamic-session KV", "It removes autoregressive order", "It guarantees factual answers"], answer: 1, explanation: "Paging maps logically contiguous session state onto non-contiguous physical blocks, improving memory management for dynamically growing KV." }]),
  readingMinutes: 19,
  keywords: [
    { term: "Prefill", definition: "The stage that processes an existing prompt in parallel and establishes initial per-layer K/V state.", espAnalogy: "Like parsing a complete handshake packet when a connection begins." },
    { term: "Decode", definition: "The stage that appends one position and generates the next token after the previous output is known.", espAnalogy: "Like an event loop advancing only after the prior state result arrives." },
    { term: "KV cache", definition: "Session state containing Key and Value projections produced by historical tokens at every layer.", espAnalogy: "Like layered indexes and data descriptors retained for validated fields." },
    { term: "GQA / MQA", definition: "Structures in which several Query heads share fewer K/V heads, reducing cache width per token.", espAnalogy: "Like several consumers sharing fewer read-only index tables." },
  ],
  recap: "The previous chapter exposed Attention's Q/K/V, causal masks, and multi-head aggregation as explicit dataflow. This chapter focuses only on reusing historical K/V during generation and the resulting session-memory, bandwidth, and reclamation responsibilities.",
  nextPreview: "Next comes LLM quantization and GGUF, connecting weights, tensor types, block overhead, metadata, and output quality in one verifiable model package.",
});

const course = [
  revise(old[0], 1, { t: "Neural Network Foundations", s: "Build neural-network intuition from tensors, layers, and loss functions", next: "Training and Inference", nextPreview: "Next, training mode, inference mode, computation graphs, weights, and format contracts become one verifiable model-delivery chain." }),
  revise(old[1], 2, {
    t: "Training and Inference", s: "Freeze learnable state into a portable, verifiable model artifact", goal: "Understand the difference between training and inference state, then turn a checkpoint into a deployment artifact with graph, weights, versions, and preprocessing contracts.",
    concept: ["Training loops and optimizer state", "Train/eval execution semantics", "Graphs, weights, and metadata", "IR, opset, and runtime compatibility", "Export, conversion, and layered equivalence tests"],
    analogy: "Like freezing a debuggable protocol-stack project into release firmware: training logs and mutable state remain in the lab, while the device receives fixed execution, constants, versions, and I/O contracts.",
    diagram: "data + labels → train state → checkpoint\n                              │ eval/freeze/export\n                              ▼\ninput contract → graph + weights + metadata → runtime/backend",
    code: "model.eval()\nexport(model, example_input, opset_version=...)\nassert_close(reference_output, runtime_output)\n# Preserve tokenizer/labels/preprocess/version too",
    lab: "Train a tiny model and save a checkpoint. Switch to eval, export ONNX or LiteRT, and list the graph, weights, opset, input shape/dtype, and preprocessing version. Use three golden inputs to compare framework, exported graph, and target-runtime outputs.",
    questions: [old[1].questions[1], old[2].questions[0], old[2].questions[2]], next: "Model Quantization",
    lesson: [old[1].lesson[0], old[1].lesson[1], old[1].lesson[2], old[2].lesson[0], old[2].lesson[2], old[2].lesson[3], old[2].lesson[4]],
    pitfall: "Saving only weights or treating successful conversion as semantic equivalence. A deployable artifact also depends on graph versions, operators, preprocessing, labels, and runtime, and every transform needs golden-vector checks.",
    references: [old[1].references[0], old[2].references[0], old[2].references[2]], quiz: [old[1].quiz[0], old[2].quiz[0], old[2].quiz[2]], readingMinutes: 20,
    keywords: [old[1].keywords[2], old[1].keywords[3], old[2].keywords[0], old[2].keywords[1]],
    recap: "Day 1 explained tensors, gradients, and one weight update. This chapter follows that mutable training state as it is frozen, converted, and delivered to a device runtime that never executes backpropagation.",
    nextPreview: "Next comes quantization: after fixing the model ABI, calibration and error evidence map floating-point values into fewer bits.",
    history: { intro: "The model-delivery chain formed from training algorithms, execution modes, graph representations, and interoperability standards. It advances “one reproducible experiment” into “one artifact preserving semantics in another runtime.”", milestones: [old[1].history.milestones[0], old[1].history.milestones[2], old[1].history.milestones[4], old[2].history.milestones[0], old[2].history.milestones[2], old[2].history.milestones[4]], bridge: "Treat checkpoints, exported graphs, weights, metadata, and preprocessing as one versioned model package, and compare outputs at every transformation boundary." },
    visual: old[2].visual, analogyDetail: old[1].analogyDetail,
  }),
  revise(old[3], 3, { t: "Model Quantization", s: "Trade fewer bits for lower storage and bandwidth", next: "Operators and Kernels", recap: "The previous chapter established delivery contracts from training state to model package. This chapter changes numeric representation, exchanging measured error for storage, bandwidth, and kernel opportunities.", nextPreview: "Next, operator contracts lead into layouts, tiling, fusion, and hardware kernels." }),
  revise(old[4], 4, { t: "Operators and Kernels", s: "Move from mathematical definitions to layouts, fusion, and hardware execution", next: "Edge Model Deployment", recap: "The previous chapter mapped floating-point values into low-bit representations. This chapter follows those values through operators, layouts, and actual kernels.", nextPreview: "Next, data, training, conversion, quantization, and firmware runtime become a complete non-LLM edge deployment loop." }),
  revise(old[5], 5, { t: "Edge Model Deployment", s: "Put non-LLM vision, audio, and sensor models onto a real device", next: "Edge Vision Pipelines", recap: "The first four chapters established model math, artifact contracts, quantization, and kernels. This chapter puts them into a real TinyML training-to-firmware loop.", nextPreview: "Next, resource budgeting and vision pipelines merge across Flash, SRAM, PSRAM, DMA, preprocessing, and stable event postprocessing." }),
  revise(old[6], 6, {
    t: "Edge Vision Pipelines", s: "Turn camera frames into stable events under memory, bandwidth, and real-time constraints", goal: "Budget peak memory and bandwidth for MCU/NPU vision, define frame-buffer, geometry, postprocessing, and ownership contracts, and accept the system with steady-state evidence.",
    concept: ["Flash, SRAM, PSRAM, and peak live memory", "DMA, stride, layout, and buffer ownership", "Classification, detection, segmentation, ROI, and letterbox", "NPU partitions, fallback, and data movement", "NMS, temporal smoothing, energy, and thermal steady state"],
    analogy: "Like a real-time video line with little floor space: warehouse capacity, conveyor bandwidth, pallet ownership, station cadence, and final inspection must be designed together.",
    diagram: "camera DMA → frame buffer → ROI/resize/letterbox → model partition\n       ▲ ownership/stride      SRAM↔PSRAM↔NPU         │\n       └──────── release ◄── NMS + temporal policy ◄──┘",
    code: "frame = camera_acquire()\ninput, transform = preprocess(frame)\nraw = infer(input)\nevent = postprocess(raw, transform)\ncamera_release(frame)\nassert peak_live_bytes <= memory_budget",
    lab: "For an ESP32 camera board, list lifetimes for frame buffers, weights, tensor arena, resize scratch, and outputs, then calculate the overlapping peak. Replay one labeled image and save the source, letterboxed input, raw output, and NMS result while verifying reversible coordinates. Run for ten minutes and record FPS, memory low-water mark, and temperature or power.",
    questions: [old[6].questions[0], old[7].questions[0], old[7].questions[1]], next: "LLM Foundations",
    lesson: [old[6].lesson[0], old[6].lesson[1], old[6].lesson[2], old[7].lesson[0], old[7].lesson[1], old[7].lesson[2], old[7].lesson[4]],
    pitfall: "Treating the model file as peak RAM or modifying a frame while DMA or the driver still owns it. Resource budgets need overlapping lifetimes, and image transforms need stride, ownership, and reversible geometry records.",
    references: [old[6].references[0], old[7].references[0], old[7].references[2]], quiz: [old[6].quiz[0], old[7].quiz[0], old[7].quiz[1]], readingMinutes: 20,
    keywords: [old[6].keywords[0], old[6].keywords[2], old[7].keywords[0], old[7].keywords[1]],
    recap: "Day 5 deployed a non-LLM model to an MCU. This chapter merges the resource ledger with the camera data path to test whether the system remains stable at real frame rates, memory pressure, and temperature.",
    nextPreview: "The next chapter is the course boundary: leave conventional discriminative edge models and enter LLMs through their history, essential terms, and capability limits.",
    history: { intro: "Edge vision grew through lightweight networks, memory hierarchy, DMA, and complete preprocessing and postprocessing. Peak compute matters only when data arrives on time, buffer lifetimes are correct, and outputs map back to the source.", milestones: [old[6].history.milestones[1], old[6].history.milestones[2], old[6].history.milestones[4], old[7].history.milestones[1], old[7].history.milestones[2], old[7].history.milestones[4]], bridge: "Put every format, geometry, ownership, and storage-tier transition for one frame in one trace, then observe memory low-water marks and timing stability during sustained operation." },
    visual: old[7].visual, analogyDetail: old[6].analogyDetail,
  }),
  day7,
  revise(old[8], 8, { next: "Transformer Architecture", recap: "The previous chapter established the LLM objective, historical path, and state vocabulary. This chapter starts at the input boundary and fixes exact contracts for characters, bytes, tokens, special markers, and message templates.", nextPreview: "Next, the Transformer becomes a standalone architecture: tokens, positions, blocks, FFNs, residuals, normalization, and logits form one complete path." }),
  day9,
  day10,
  day11,
  revise(old[11], 12, { t: "LLM Quantization and GGUF", s: "Package low-bit weights and metadata into a deployable model artifact", next: "LLM Runtime", recap: "The previous chapter established a capacity ledger for KV state that grows token by token. This chapter compresses the weights reused across requests and treats GGUF metadata as a verifiable model-package contract.", nextPreview: "Next, the model package enters a real runtime and on-device framework, exposing loading, sampling, scheduling, backend partitions, fallback, and cancellation paths." }),
  revise(old[10], 13, {
    t: "LLM Runtime",
    s: "Organize model packages, generation loops, and heterogeneous backends into an observable execution path",
    goal: "Understand how a runtime loads models, manages sessions, schedules Prefill and Decode, samples, streams, and cancels, then compare CPU, GPU, and NPU backends, compilation modes, subgraph partitions, and fallback with a layered acceptance matrix.",
    concept: ["Model loading, mmap, and process resources", "Prefill/Decode, sampling, streaming, and cancellation", "Runtime, graph compiler, backend, and hardware layers", "CPU/GPU/NPU partitions and boundary copies", "Fallback, observability, and framework acceptance"],
    analogy: "Like a dispatch workshop with several production lines: the runtime accepts jobs, owns work in progress, and sets cadence; a compiler creates routes; each backend executes supported operations; every cross-line transfer and rework event must be recorded.",
    diagram: "model package → loader/compiler → runtime request loop\n                                  │\n       CPU baseline ↔ GPU delegate ↔ NPU partition\n queue → prefill → decode → sample → stream / cancel / reclaim",
    code: "engine = load(model_package, backend_policy)\nfor request in scheduler:\n    state = prefill(request.tokens)\n    while not request.done:\n        logits, state = decode_one(state)\n        request.stream(sampler(logits))\n    reclaim(state)  # cancellation and errors share this path",
    lab: "Choose one local LLM and two available execution configurations. Fix the model, GGUF, prompt, threads, context, and output length. Establish a CPU correctness baseline, then enable a GPU/NPU delegate or offload. Record load time, TTFT, ITL, peak RSS, actual operator or layer partitions, boundary copies, fallback, and resource reclamation after cancellation. Compare output tokens and logs with the same golden prompts in a one-page framework matrix.",
    questions: [old[10].questions[0], old[12].questions[0], old[12].questions[2]],
    next: "LLM Performance and Infrastructure",
    lesson: [old[10].lesson[0], old[10].lesson[2], old[10].lesson[3], old[12].lesson[0], old[12].lesson[1], old[12].lesson[2], old[12].lesson[4]],
    pitfall: "Treating model loading as completed framework support, or comparing only brands and peak tokens/s. Prove tokenizer and template consistency, actual target-backend placement, explainable boundary copies, visible fallback, and complete session-state reclamation after cancellation and failure.",
    references: [["Official llama.cpp repository", "https://github.com/ggml-org/llama.cpp"], old[12].references[0], old[12].references[1]],
    quiz: [old[10].quiz[0], old[12].quiz[0], old[12].quiz[2]],
    readingMinutes: 20,
    keywords: [old[10].keywords[0], old[10].keywords[3], old[12].keywords[0], old[12].keywords[1]],
    recap: "The first six days established the conventional edge-model execution chain, and Days 7–12 added LLM inputs, architecture, Attention, KV, and model packages. This chapter places those static contracts inside a real runtime so request scheduling and heterogeneous backends become one traceable data and control path.",
    nextPreview: "Next, single-machine benchmarks expand into chips, interconnects, parallel training, online serving, and SLOs as one cross-scale evidence chain.",
    history: {
      intro: "LLM runtimes and on-device frameworks jointly connect model semantics to hardware reality. One manages generation state and request lifecycles; the other maps operators to heterogeneous devices through graph transforms, compilation, and delegates. Their histories meet in an execution path that must be observable and reversible.",
      milestones: [old[10].history.milestones[0], old[10].history.milestones[2], old[10].history.milestones[4], old[12].history.milestones[0], old[12].history.milestones[2], old[12].history.milestones[4]],
      bridge: "Fix semantics with a CPU baseline and golden inputs, then enable the quantized package, compiler transforms, subgraph partitions, and hardware delegates one layer at a time. Every optimization layer must leave evidence for actual placement, copy boundaries, versions, and fallback.",
    },
    visual: old[12].visual,
    analogyDetail: old[10].analogyDetail,
  }),
  revise(old[15], 14, {
    t: "LLM Performance and Infrastructure", s: "Trace single-machine TTFT and ITL into cluster data movement, topology, and SLOs", goal: "Use reproducible experiments to localize device inference bottlenecks, then understand how training parallelism, KV scheduling, Prefill/Decode disaggregation, and serving SLOs extend the same ledger to clusters.",
    concept: ["TTFT, ITL, throughput, and percentiles", "Roofline, bandwidth, energy, and thermal steady state", "DP/TP/PP/CP/EP and communication topology", "KV, continuous batching, and PD disaggregation", "Training goodput, serving SLOs, and recovery"],
    analogy: "Like tracing one late train into an entire rail network: fix the vehicle schedule and load first, then analyze station transfers, line bandwidth, dispatch policy, and on-time objectives.",
    diagram: "request → queue → prefill → decode → stream\n             │ TTFT      │ ITL / KV\nchip memory ↔ scale-up ↔ scale-out ↔ storage\n             └── topology + parallelism + SLO ──┘",
    code: "record(model, quant, prompt_tokens, output_tokens, hardware, temperature)\nmeasure(TTFT, ITL_p50, ITL_p95, tokens_per_s, joules_per_token)\n# At cluster scale, add collectives, KV occupancy, goodput, and recovery",
    lab: "Fix model, quantization, prompt, and output length. Run one cold and ten warmed local trials, recording TTFT, ITL p50/p95, RSS, power, and temperature. Then place one request on a chip-memory→scale-up→scale-out→storage map. For TP, PP, sharded training, or PD disaggregation, label every new communication edge and the metric it may improve or worsen.",
    questions: [old[13].questions[0], old[15].questions[1], old[15].questions[2]], next: "Shipping Edge LLMs",
    lesson: [old[13].lesson[0], old[13].lesson[1], old[13].lesson[2], old[15].lesson[0], old[15].lesson[1], old[15].lesson[3], old[15].lesson[6]],
    pitfall: "Reporting peak tokens/s alone or treating one parallel/disaggregated strategy as universally faster. Results must bind model, precision, sequence, concurrency, topology, thermal state, and SLO; boundary communication can erase local gains.",
    references: [old[13].references[0], old[15].references[0], old[15].references[2]], quiz: [old[13].quiz[0], old[15].quiz[1], old[15].quiz[2]], readingMinutes: 20,
    keywords: [old[13].keywords[0], old[13].keywords[1], old[15].keywords[0], old[15].keywords[3]],
    recap: "Day 13 proved which backends a request actually traversed. This chapter upgrades that correctness baseline into a cross-scale performance ledger, extending device measurements into cluster communication, state scheduling, and service objectives.",
    nextPreview: "The final chapter closes model packages, runtimes, heterogeneous backends, MCU/host safety boundaries, energy, fallback, OTA, and observability into a deliverable edge-LLM product.",
    analogyDetail: old[13].analogyDetail,
  }),
  revise(old[16], 15, {
    t: "Shipping Edge LLMs", s: "Close models, heterogeneous hardware, MCU/host boundaries, and operational evidence into a shippable system", goal: "Complete the three-tier responsibility boundary, model-package contract, heterogeneous execution, capacity and energy budget, degradation behavior, version release, and acceptance report for an edge LLM.",
    concept: ["MCU, Edge Host, and cloud responsibility tiers", "Model package, tokenizer, runtime, and backend contracts", "Weights, activations, KV, workspace, and peak RSS", "Tool-call safety boundaries, explicit fallback, and degradation", "Quality, experience, energy, thermals, OTA, and observability"],
    analogy: "Like fitting a cloud kitchen into a constrained food truck: menu, equipment, storage, power, hygiene rules, and emergency routes must be accepted as one system.",
    diagram: "sensor/actuator ↔ MCU deterministic gate ↔ Edge Host LLM\n                         │ validate tool proposal │\n                         └── explicit cloud fallback\nmodel package → runtime/backend → telemetry → staged OTA/rollback",
    code: "proposal = edge_llm(request)\nvalidated = policy_and_schema_check(proposal)\nif validated:\n    mcu_execute(validated)\nelse:\n    enter_safe_degraded_state()\nrecord(version_set, latency, energy, thermal, failures)",
    lab: "Write a one-page acceptance contract for an ESP32 + Edge Host project. Define which actions the model may propose and how the MCU validates them. Pin model, tokenizer, template, runtime, backend, firmware, and protocol versions. Budget weights, KV, workspace, I/O, and peak RSS; run sustained TTFT, ITL, energy, thermal, and failure tests. Drill host loss, load failure, timeout, invalid tool arguments, and OTA rollback.",
    questions: [old[14].questions[0], old[16].questions[0], old[16].questions[1]], next: null,
    lesson: [old[14].lesson[0], old[14].lesson[1], old[14].lesson[2], old[16].lesson[1], old[16].lesson[2], old[16].lesson[3], old[16].lesson[6]],
    pitfall: "Giving natural-language output direct actuation authority or accepting one successful demo. A shippable system validates actions inside deterministic boundaries and closes acceptance with versioned steady-state evidence, failure drills, and rollback.",
    references: [old[14].references[1], old[16].references[0], old[16].references[2]], quiz: [old[14].quiz[0], old[16].quiz[0], old[16].quiz[1]], readingMinutes: 20,
    keywords: [old[14].keywords[0], old[16].keywords[0], old[16].keywords[1], old[16].keywords[3]],
    recap: "The first fourteen days progressed from neural foundations to LLM structure, runtimes, quantization, frameworks, and cross-scale performance. This chapter compresses everything into a product: who has authority, where every byte and joule goes, how failure remains safe, and how versions ship and roll back.",
    nextPreview: "The 15-day route is complete. Start the next project from its target device and real workload: write safety and acceptance boundaries first, then select model and runtime, and leave reproducible evidence for every optimization.",
  }),
];

module.exports = course;
