const core = require("./zh-CN.json");
const advanced = require("./zh-16-17.cjs");

const old = [...core, ...advanced];
const copy = value => structuredClone(value);
const revise = (source, n, overrides) => ({ ...copy(source), ...overrides, n });

const day7 = {
  n: 7,
  t: "LLM 基础",
  s: "从语言模型起源建立发展脉络、工作原理与关键术语地图",
  goal: "理解 LLM 从统计语言模型、神经语言模型到 Transformer、预训练与指令对齐的发展脉络，并能准确解释 token、参数、上下文、预训练、推理与幻觉等核心术语。",
  concept: [
    "语言模型与 next-token prediction",
    "token、embedding、参数与上下文窗口",
    "预训练、微调、指令对齐与推理",
    "规模化、涌现能力与基础模型",
    "概率生成、幻觉与能力边界",
  ],
  analogy: "把 LLM 看成一个由海量文本训练出的概率协议栈：token 是帧单元，参数是固化的统计状态，上下文是当前会话缓冲区，推理则是逐帧预测下一段最可能的数据。",
  diagram: "文本语料 ──tokenize──► token 序列 ──预训练：预测下一个 token──► 基础模型\n用户指令 ──template──► context ──逐 token 推理──► 概率分布 ──sampling──► 输出",
  code: "tokens = tokenizer(chat_template(messages))\nfor token in tokens:\n    state = model(token, state)\nwhile not stop:\n    logits, state = model(next_token, state)\n    next_token = sample(logits)",
  lab: "选择一句中英文混合提示，先记录字符数，再用任意开源 tokenizer 得到 token 数；随后用同一模型分别以 temperature=0 与较高 temperature 生成三次，记录输出差异。最后画出“语料→预训练→基础模型→指令对齐→部署推理”的五段链路，并给每段写出输入、输出和不能保证的事情。",
  questions: [
    "语言模型为什么可以通过预测下一个 token 学到可迁移的语言与知识模式？",
    "参数、上下文窗口与 KV cache 分别属于哪类状态，生命周期有何不同？",
    "指令对齐改善了什么，又为什么不能消除幻觉？",
  ],
  next: "Tokenizer",
  lesson: [
    {
      title: "先从任务定义开始：LLM 是条件概率模型",
      body: "语言模型学习的是在已有 token 前缀条件下，下一个 token 的概率分布。训练时把真实序列向右错一位形成监督信号，一段文本就能贡献许多预测样本；推理时则从分布中选择一个 token，再把它追加到前缀继续预测。这个统一目标能迫使模型压缩语法、语义、事实共现与任务格式，但它优化的是预测似然，不是事实数据库的一致性、逻辑证明的完备性或现实世界的安全性。",
    },
    {
      title: "从统计计数到分布式表示，核心问题一直是泛化",
      body: "早期 n-gram 语言模型按有限历史统计下一个词，简单、可解释，却容易遭遇未见组合和维度爆炸。神经语言模型用 embedding 把离散词映射到连续空间，并用共享参数在相似上下文之间迁移统计强度。word2vec 等方法进一步展示分布式表示的可复用性。LLM 并非突然出现的魔法，而是语言建模目标、表示学习、计算规模与数据工程长期汇合的结果。",
    },
    {
      title: "Transformer 让长依赖与大规模并行训练更可行",
      body: "循环网络必须沿序列逐步传递状态，长路径让训练并行与远距离信用分配都更困难。Transformer 用 self-attention 建立 token 间的直接交互，再叠加逐位置前馈网络、残差连接、归一化与位置机制，使训练阶段可以并行处理整段序列。它并没有让自回归生成失去先后顺序；输入处理与输出生成是两种不同的计算形态，后续章节会分别拆解 Attention、Prefill、Decode 与 KV cache。",
    },
    {
      title: "预训练、微调与对齐是三种不同责任",
      body: "预训练从大规模语料学习通用表示和生成能力；监督微调用更小、更明确的数据塑造任务格式；指令对齐再用偏好数据或规则，让回答更符合人的意图与安全约束。三者都改变权重，却使用不同数据、目标和验收标准。工程上还要区分 prompt 内学习：它只在当前上下文中提供示例，并不会永久修改参数。把这些过程混称为“训练一下”会导致成本、隐私和可回滚性判断错误。",
    },
    {
      title: "规模带来能力，也放大数据、评估与系统问题",
      body: "参数量、训练数据和计算量共同扩大模型容量，但任一数字都不能单独代表能力。更大的模型可能展现更强的少样本迁移和任务泛化，也会需要更高训练成本、更多权重存储、更多推理带宽和更严格的数据治理。所谓基础模型强调一个预训练模型可适配许多下游任务；它不是“懂一切”的认证。比较模型时应固定任务、提示模板、上下文、精度、硬件和评估集。",
    },
    {
      title: "把常见术语放回正确的生命周期",
      body: "token 是 tokenizer 定义的离散编号；embedding 是编号进入模型后的向量；参数是训练后冻结并跨请求复用的长期状态；context 是本次请求可见的 token 序列；KV cache 是该序列在各层产生的临时中间状态；logits 是下一 token 的未归一化分数；sampling 决定如何从分布选出输出。术语一旦归位，模型文件、会话内存、服务调度与产品体验就能进入同一张资源账本。",
    },
    {
      title: "概率流畅不等于事实可靠，能力必须用证据界定",
      body: "模型会根据训练分布和当前上下文补全最可能的文本，因此可以生成语法流畅但事实错误、来源虚构或前后矛盾的内容。检索、工具调用、结构化约束和人工复核能降低风险，却不能把概率模型自动变成真值机。端侧产品要标出允许模型建议的范围，把设备控制、安全判断和不可逆操作留在确定性验证边界内，并用真实失效样本持续评估。",
    },
  ],
  pitfall: "把参数量当成智能刻度，或把流畅回答当成已验证事实。LLM 的能力取决于数据、训练目标、提示、上下文与评估任务；生成结果进入设备动作前必须经过确定性校验。",
  references: [
    ["神经概率语言模型原始论文", "https://www.jmlr.org/papers/v3/bengio03a.html"],
    ["《Attention Is All You Need》原始论文", "https://arxiv.org/abs/1706.03762"],
    ["GPT-3 原始论文", "https://arxiv.org/abs/2005.14165"],
  ],
  quiz: [
    {
      prompt: "LLM 预训练中最典型的自监督目标是什么？",
      options: ["记住每篇文档的文件名", "根据已有 token 预测下一个 token", "把所有句子压成同一向量", "直接验证现实世界事实"],
      answer: 1,
      explanation: "自回归语言模型从已有前缀预测下一个 token；同一目标可从未标注文本自动构造大量训练信号。",
    },
    {
      prompt: "哪项最准确地区分参数与上下文？",
      options: ["两者都会在每个 token 后永久更新", "参数跨请求复用，上下文属于当前请求可见序列", "上下文存于模型权重文件", "参数就是 tokenizer 词表"],
      answer: 1,
      explanation: "参数是训练形成并在推理时复用的模型状态；上下文是一次会话或请求中的 token 序列。",
    },
    {
      prompt: "为什么经过指令对齐的模型仍可能幻觉？",
      options: ["因为对齐会删除 tokenizer", "因为生成目标仍是条件概率预测，对齐不能保证每个陈述都真实", "因为 KV cache 一定损坏", "因为所有模型只能处理英文"],
      answer: 1,
      explanation: "对齐能改善行为和偏好，但不能把概率生成目标变成事实证明系统，重要输出仍需外部证据。",
    },
  ],
  readingMinutes: 20,
  keywords: [
    { term: "语言模型", definition: "估计 token 序列概率或下一个 token 条件概率的模型。", espAnalogy: "像根据已收到的协议字段预测下一字段类型与取值范围。" },
    { term: "参数", definition: "训练得到并在推理时固定复用的权重，是模型的长期统计状态。", espAnalogy: "像编译进固件、跨请求复用的查表常量和控制系数。" },
    { term: "预训练 / 对齐", definition: "预训练学习通用模式；对齐用指令、偏好或规则塑造可用行为。", espAnalogy: "像先训练通用协议解析器，再按产品规范收紧命令与错误处理。" },
    { term: "幻觉", definition: "模型生成流畅但不受事实证据支持或与现实不一致的内容。", espAnalogy: "像校验和正确、格式完整，但 payload 语义仍然错误的数据包。" },
  ],
  recap: "前六天已经建立从神经网络、模型产物到端侧资源与视觉流水线的传统 AI 工程闭环。今天从模型类别切换到生成式语言模型，先建立一张不会被工具名和参数量带偏的全局地图。",
  nextPreview: "下一章进入 Tokenizer：追踪文本如何变成 token id，并把词表、特殊 token 与 chat template 视为模型 ABI。",
  history: {
    intro: "LLM 的形成不是单一论文带来的跳跃，而是语言概率建模、分布式表示、并行架构、规模化预训练和人类偏好对齐逐步叠加的结果。理解这些典型时刻，才能分清哪些能力来自训练目标，哪些来自结构，哪些来自部署时的系统工程。",
    milestones: [
      { year: "1948", title: "信息论为语言的概率与不确定性提供度量", body: "Shannon 用熵与条件概率研究通信和英文序列的可预测性，奠定了把语言视为随机过程、用上下文降低不确定性的思想起点。", source: { label: "Shannon 原始论文", url: "https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf" } },
      { year: "2003", title: "神经概率语言模型学习分布式词表示", body: "Bengio 等人用共享的连续词向量和神经网络估计下一个词概率，使相似上下文可以共享统计强度，缓解传统 n-gram 的维度灾难。", source: { label: "神经概率语言模型原始论文", url: "https://www.jmlr.org/papers/v3/bengio03a.html" } },
      { year: "2017", title: "Transformer 以 Attention 重写序列建模主干", body: "《Attention Is All You Need》移除循环和卷积主干，用 self-attention、前馈网络、残差与位置编码构建可并行训练的 encoder–decoder。", source: { label: "Transformer 原始论文", url: "https://arxiv.org/abs/1706.03762" } },
      { year: "2018", title: "BERT 证明大规模预训练可迁移到多种理解任务", body: "BERT 通过双向 Transformer 预训练后再微调，在多项自然语言理解任务上展示“一个基础表示、多种下游适配”的范式。", source: { label: "BERT 原始论文", url: "https://arxiv.org/abs/1810.04805" } },
      { year: "2020", title: "GPT-3 展示规模化自回归模型的上下文学习", body: "GPT-3 在不更新参数的情况下，通过提示中的描述或少量示例完成多类任务，使规模、prompt 与 in-context learning 成为重要研究和产品变量。", source: { label: "GPT-3 原始论文", url: "https://arxiv.org/abs/2005.14165" } },
      { year: "2022", title: "InstructGPT 把指令遵循与人类偏好引入对齐链", body: "监督指令数据、奖励模型与人类反馈强化学习被组合起来，让基础模型更倾向于遵循用户意图，同时也暴露出对齐评估与安全边界的重要性。", source: { label: "InstructGPT 原始论文", url: "https://arxiv.org/abs/2203.02155" } },
    ],
    bridge: "今天的本地或端侧 LLM 仍沿用这条链：tokenizer 定义输入，Transformer 权重承载预训练与对齐结果，runtime 管理上下文与逐 token 生成。设备工程优化的是表示、状态和数据移动，不能改变模型原本没有学会或无法可靠保证的事情。",
  },
  visual: {
    title: "一条语言能力如何从语料进入一次回答",
    description: "播放器把长期训练阶段与一次请求的短期推理阶段分开，避免把参数更新、上下文和缓存混成同一件事。",
    steps: [
      { icon: "📚", label: "收集与治理语料", data: "documents + provenance", action: "清洗、去重、过滤并记录来源", insight: "模型能力与风险都从数据分布开始" },
      { icon: "🔤", label: "切成 token", data: "text → token ids", action: "按固定词表和规范化规则编码", insight: "字符数不等于模型看到的序列长度" },
      { icon: "🏋️", label: "预训练", data: "prefix → next token", action: "反复计算损失并更新参数", insight: "通用模式进入跨请求复用的权重" },
      { icon: "🧭", label: "指令对齐", data: "instruction + preference", action: "塑造回答格式、帮助性与安全行为", insight: "行为改善不等于事实保证" },
      { icon: "💬", label: "构造上下文", data: "system + history + user", action: "应用模板并形成当前可见前缀", insight: "上下文只属于本次会话" },
      { icon: "✨", label: "逐 token 生成", data: "logits → sample → append", action: "预测、选择、追加并重复", insight: "每一步输出都会成为下一步输入" },
    ],
    loop: "生成阶段从“逐 token 生成”回到自身，直到 EOS、长度上限或取消；只有离线训练或微调才会回到参数更新。",
  },
  analogyDetail: {
    title: "一套持续修订、现场只读的协议预测固件",
    story: "研发中心先用大量历史报文训练一套预测固件，把常见结构压进参数；产品团队再用规范样例校正它如何响应指令。设备收到一次新请求时，只加载固定固件，把当前报文放入会话缓冲区，逐段预测后续内容。预测可以很流畅，但关键字段仍必须通过确定性协议校验。",
    illustration: [
      { icon: "📦", label: "历史报文仓库", mapsTo: "预训练语料与数据治理" },
      { icon: "💾", label: "预测固件", mapsTo: "冻结并跨请求复用的模型参数" },
      { icon: "🧾", label: "当前报文缓冲", mapsTo: "本次请求的 token 上下文" },
      { icon: "✅", label: "协议校验器", mapsTo: "工具、规则、检索与人工复核边界" },
    ],
    boundary: "LLM 参数不是可逐条查询的数据库，token 也不等于协议中的固定语义字段；类比只用于区分训练期长期状态、请求期短期状态与外部校验责任。",
  },
};

const day9 = {
  n: 9,
  t: "Transformer 架构",
  s: "先看清整座模型，再深入其中的 Attention 数据流",
  goal: "理解 Transformer 如何把 embedding、位置机制、Attention、FFN、残差连接和归一化组织为 encoder、decoder 与 decoder-only 架构，并能从模型配置还原一次从 token 到 logits 的完整前向路径。",
  concept: ["Encoder、Decoder 与 decoder-only", "Embedding、位置机制与输出头", "Transformer block 与层堆叠", "Residual、LayerNorm 与 FFN", "训练并行与生成顺序"],
  analogy: "像先阅读一块 SoC 的总框图：输入接口、互连、计算单元、旁路和输出控制各有职责；Attention 是互连核心，但不能替代整颗芯片的架构说明。",
  diagram: "token ids → embedding + position → N × Transformer block → final norm → logits\n                                     │\n                 Attention → residual → FFN → residual",
  code: "x = token_embedding(token_ids) + position(position_ids)\nfor block in transformer_blocks:\n    x = block(x, mask=causal_mask)\nlogits = output_head(final_norm(x))",
  lab: "选择一个开源 decoder-only 模型，阅读其 config 与结构打印结果，记录 vocab size、hidden size、层数、attention heads、KV heads、FFN intermediate size、位置机制和是否共享输入输出 embedding。画出一个 block 的张量形状，并用参数量近似式分别估算 embedding、Attention 和 FFN 的占比；最后用短序列确认输出 logits 的 shape。",
  questions: ["Encoder、encoder–decoder 与 decoder-only 架构的可见信息和输出目标有何不同？", "为什么 Attention 之外还需要逐位置 FFN、残差连接和归一化？", "为什么整段训练输入能并行经过层堆叠，而自回归生成仍要逐 token 推进？"],
  next: "Attention 机制",
  lesson: [
    { title: "先把 Transformer 看成架构，而不是一个公式", body: "Transformer 是一套组织序列计算的骨架：token 先进入 embedding 与位置机制，再依次经过多个 block，最后由归一化和输出头产生 logits。每个 block 内部通常包含跨位置交换信息的 Attention、逐位置变换表示的 FFN，以及维持深层信号路径的残差和归一化。先固定这些模块的输入输出与重复关系，下一章再展开 Attention 内部的 Q、K、V，才能避免用一个公式代替整个模型。" },
    { title: "Encoder、Decoder 与 decoder-only 服务不同的信息流", body: "Encoder 让每个位置读取完整输入，适合构造上下文相关表示；原始 decoder 既对已生成前缀做 causal self-attention，又通过 cross-attention 读取 encoder 输出；decoder-only 模型则把指令、上下文和答案放进同一条因果序列，统一执行 next-token prediction。三类结构共享 block 思想，却有不同 mask、输入契约和训练目标，不能只凭都叫 Transformer 就假设模型可互换。" },
    { title: "Embedding、位置与输出头定义序列的两端", body: "Token id 本身只是离散索引，输入 embedding 把它映射为 hidden vector；位置编码或旋转位置机制再让模型区分顺序和距离。层堆叠输出的 hidden state 经过 final norm 与线性输出头映射回词表 logits，有些模型会让输出权重与输入 embedding 共享。部署时 vocab size、hidden size、位置参数和权重共享方式都会改变文件大小、算子 shape 与兼容性，因此它们属于模型包契约。" },
    { title: "FFN 是每个位置上的主要非线性计算路径", body: "Attention 混合不同位置的信息，FFN 则对每个位置独立应用相同参数的扩展、激活和压缩。经典 Transformer 使用两层前馈网络，现代 LLM 常见 gated MLP 等变体；intermediate size 和激活形式会显著影响参数量、内存带宽与 kernel 覆盖。分析模型时应分别统计 Attention 投影与 FFN 权重，而不是把 block 成本全部归因于 Attention。" },
    { title: "残差与归一化决定深层网络怎样稳定传递", body: "残差连接为每个子层提供短路径，使深层堆叠仍能保留和修正已有表示；LayerNorm 或 RMSNorm 控制数值尺度。不同模型可能采用 pre-norm、post-norm、并行残差或不同归一化形式，这些差异会改变执行顺序，不能在转换时随意调换。验证一个 backend 时，应在 block 边界保存金向量，先定位是归一化、残差相加还是子层计算发生偏差。" },
    { title: "训练并行与生成串行发生在不同维度", body: "训练时完整目标序列已知，causal mask 可以阻止未来信息泄漏，同时让同一层的多个位置批量计算；层与层之间仍按拓扑依赖前进。生成时下一个 token 尚未确定，必须等本轮 logits 经采样得到结果后才能构造新位置。Transformer 缩短了位置间的信息路径并提高训练并行度，却没有消除自回归输出的时间依赖；这正是后续 Attention 与 KV Cache 工程的起点。" },
  ],
  pitfall: "把 Transformer 等同于 Attention，或看到“可并行”就认为层之间和生成步骤之间都能任意并行。完整架构还包括 embedding、位置、FFN、残差、归一化和输出头；并行性必须说明发生在 batch、序列位置、head、张量还是层流水线上。",
  references: [["《Attention Is All You Need》原始论文", "https://arxiv.org/abs/1706.03762"], ["BERT 原始论文", "https://arxiv.org/abs/1810.04805"], ["GPT-3 原始论文", "https://arxiv.org/abs/2005.14165"]],
  quiz: [
    { prompt: "在 Transformer block 中，FFN 的主要职责是什么？", options: ["为每个位置应用共享的非线性表示变换", "决定 tokenizer 如何切词", "永久保存所有会话 KV", "替代 residual connection"], answer: 0, explanation: "Attention 负责跨位置交换信息，FFN 对每个位置独立应用共享参数的非线性变换。" },
    { prompt: "decoder-only LLM 最典型的可见性约束是什么？", options: ["每个位置都能读取未来答案", "所有位置只能读取自己", "每个位置只能读取当前及之前的 token", "只能读取图像 patch"], answer: 2, explanation: "Causal 可见性让当前位置使用当前及更早的前缀，同时阻止训练标签从未来泄漏。" },
    { prompt: "哪项最准确地描述 Transformer 的训练并行与生成顺序？", options: ["训练和生成都不含顺序依赖", "已知训练序列的位置可并行计算，但生成的新 token 仍依赖上一步结果", "只有 FFN 可以训练", "层堆叠可以倒序执行"], answer: 1, explanation: "训练时完整序列已知并由 mask 保持因果语义；生成时下一位置的输入必须等待上一 token 被选出。" },
  ],
  readingMinutes: 20,
  keywords: [
    { term: "Transformer block", definition: "由 Attention、FFN、残差与归一化等子层组成并重复堆叠的序列计算单元。", espAnalogy: "像 SoC 中重复布置的计算 tile，每块都有互连与本地处理路径。" },
    { term: "Decoder-only", definition: "只堆叠带因果可见性的 decoder 风格 block，以统一的序列目标生成下一个 token。", espAnalogy: "像只根据已经接收的协议前缀持续推进的状态机。" },
    { term: "FFN / MLP", definition: "在每个序列位置独立执行、各位置共享参数的非线性前馈子层。", espAnalogy: "像每个数据包都经过同一套本地字段变换单元。" },
    { term: "Residual + Norm", definition: "用短路径保留已有表示，并控制深层堆叠中的数值尺度。", espAnalogy: "像主数据旁路与逐级电平校准共同维持长流水线稳定。" },
  ],
  recap: "Day 7 建立 LLM 的历史与术语地图，Day 8 固定文本输入 ABI。本章把 Transformer 作为独立的架构概念，先看清从 token、block 到 logits 的整体路径。",
  nextPreview: "下一章在 Day 10 单独深入 Attention：从对齐思想、Q/K/V 与 causal mask 走到多头计算、二次复杂度和 I/O-aware 实现。",
  history: {
    intro: "Transformer 的发展不是 Attention 公式单独扩张的历史，而是架构骨架、预训练目标、位置机制和规模化方法共同演进的过程。不同分支保留了相似 block，却选择不同信息流来解决理解、生成与长上下文问题。",
    milestones: [
      { year: "2017", title: "Transformer 建立无循环的 encoder–decoder 骨架", body: "原始论文用多头 Attention、逐位置 FFN、残差、LayerNorm 与位置编码组成可堆叠 block，使序列位置在训练时可以高度并行。", source: { label: "Transformer 原始论文", url: "https://arxiv.org/abs/1706.03762" } },
      { year: "2018", title: "GPT 验证 decoder 预训练后迁移的路线", body: "生成式预训练把多层 Transformer decoder 用于通用语言建模，再通过任务微调迁移，奠定 decoder-only 路线的重要起点。", source: { label: "GPT 原始论文", url: "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf" } },
      { year: "2018", title: "BERT 强化双向 encoder 预训练", body: "BERT 通过 masked language modeling 使用双向上下文，展示 encoder-only Transformer 可以形成可迁移的语言理解表示。", source: { label: "BERT 原始论文", url: "https://arxiv.org/abs/1810.04805" } },
      { year: "2019", title: "Transformer-XL 延伸跨片段依赖", body: "循环使用片段级隐藏状态并引入相对位置编码，让架构在固定训练片段之外保留更长历史，同时明确状态复用的边界。", source: { label: "Transformer-XL 原始论文", url: "https://arxiv.org/abs/1901.02860" } },
      { year: "2020", title: "GPT-3 展示大规模 decoder-only 的上下文学习", body: "GPT-3 扩大自回归 Transformer，并用提示中的描述和示例完成任务，使 decoder-only、规模化和 in-context learning 成为主线。", source: { label: "GPT-3 原始论文", url: "https://arxiv.org/abs/2005.14165" } },
      { year: "2021", title: "Switch Transformer 探索稀疏专家扩展 FFN", body: "稀疏路由让每个 token 只激活部分专家 FFN，以条件计算扩大参数容量，也把路由、负载均衡和通信带入架构成本。", source: { label: "Switch Transformer 原始论文", url: "https://arxiv.org/abs/2101.03961" } },
    ],
    bridge: "端侧部署首先要从 config 和计算图识别模型属于哪种 Transformer、每个 block 有哪些子层、位置与输出头采用什么契约；随后才能分别优化 Attention、FFN、KV 和 backend。",
  },
  visual: {
    title: "一串 token 如何穿过完整 Transformer",
    description: "播放器展示模型级路径，刻意把 Attention 保留为一个待展开的子层，以便下一章专门研究其内部计算。",
    steps: [
      { icon: "🔢", label: "接收 token id", data: "[batch, sequence]", action: "读取 tokenizer 产生的离散编号", insight: "词表与模型 embedding 必须匹配" },
      { icon: "🧭", label: "加入位置", data: "token vector + position", action: "建立内容表示与顺序信息", insight: "位置机制是模型配置的一部分" },
      { icon: "🔀", label: "跨位置交互", data: "Attention sublayer", action: "让每个位置读取允许可见的上下文", insight: "内部 Q/K/V 留到 Day 10 展开" },
      { icon: "🧱", label: "残差与归一化", data: "skip + normalize", action: "合并子层结果并稳定数值", insight: "执行顺序不能在转换时随意改动" },
      { icon: "⚙️", label: "逐位置 FFN", data: "hidden → intermediate → hidden", action: "应用共享的非线性变换", insight: "FFN 常占据显著权重与带宽" },
      { icon: "📊", label: "映射为 logits", data: "hidden → vocabulary", action: "由输出头产生下一 token 分数", insight: "logits 还不是最终 token" },
    ],
    loop: "Attention、残差、归一化与 FFN 按模型定义重复 N 层；自回归生成选出 token 后，再让新增位置重新走过整座层堆叠。",
  },
  analogyDetail: {
    title: "先看 SoC 总框图，再打开互连模块",
    story: "输入编号先经过接口和地址标记，随后穿过多块重复计算 tile。每块 tile 既有负责跨端口交换信息的互连，也有本地非线性处理、旁路与电平校准。最终输出单元把内部状态映射成词表分数。只研究互连会漏掉大部分权重、执行顺序和兼容契约。",
    illustration: [
      { icon: "🧭", label: "输入接口与地址", mapsTo: "Token embedding 与位置机制" },
      { icon: "🔀", label: "片上互连", mapsTo: "Attention 子层的跨位置通信" },
      { icon: "⚙️", label: "本地计算 tile", mapsTo: "逐位置 FFN / MLP" },
      { icon: "📊", label: "输出编码器", mapsTo: "Final norm、输出头与 logits" },
    ],
    boundary: "Transformer 不是实际 SoC，层也不一定对应独立硬件单元；类比只用于区分模型总架构、重复 block、跨位置通信和本地计算职责。",
  },
};

const day10 = revise(old[9], 10, {
  t: "Attention 机制",
  s: "把序列依赖变成可并行计算的显式数据流",
  goal: "从 Attention 的对齐问题出发，理解缩放点积、Query、Key、Value、多头注意力、causal mask 与位置交互，并能说明其并行优势、二次复杂度和 I/O 边界。",
  concept: ["Query、Key、Value 与缩放点积", "Self-attention、cross-attention 与 multi-head", "causal mask 与位置编码", "Residual、LayerNorm 与 FFN", "并行路径、O(n²) 与 I/O 代价"],
  analogy: "像一个可编程交换矩阵：每个输入位置生成查询，按内容匹配所有可见位置的索引，再对取回的数据加权聚合；多头相当于并行运行多套匹配规则。",
  diagram: "token ids → embedding + position\n                 │\nQ = XWq, K = XWk, V = XWv\n                 │\nscores = QKᵀ/√dₖ + mask → softmax → weighted V\n                 │\n          residual + norm → FFN → residual + norm",
  code: "scores = Q @ K.T / sqrt(d_k)\nscores = scores + causal_mask\nweights = softmax(scores, axis=-1)\ncontext = weights @ V\noutput = concat(heads) @ W_o",
  lab: "读《Attention Is All You Need》的摘要、第 3.1–3.5 节与第 4 节。用 4 个 token、2 维向量手算并实现 softmax(QKᵀ/√d_k)V；切换 causal mask，确认位置 i 的输出不依赖未来位置。最后将序列长度从 4 翻倍到 8、16，记录 attention score 矩阵元素数如何增长。",
  questions: ["为什么点积要除以 √d_k？", "多头注意力相比单头增加了什么表达自由度？", "为什么 Transformer 训练可并行，而自回归生成仍有顺序？"],
  next: "KV Cache",
  lesson: old[9].lesson.slice(0, 4).concat([
    { title: "一个 Transformer block 不只有 Attention", body: "Attention 负责让位置之间交换信息，逐位置 FFN 则对每个位置应用相同的非线性变换；残差连接为深层网络保留短路径，LayerNorm 稳定各层数值尺度。工程分析应把 QKV 投影、attention score、value 聚合、输出投影和 FFN 分开记账。现代 LLM 中 FFN 权重往往占据大量参数，而长上下文下 attention 的中间矩阵和 K/V 状态又成为显著内存与带宽来源。" },
    { title: "Self-attention 的优势来自路径与并行，不是免费计算", body: "论文用每层复杂度、必须串行的操作数和任意位置间最大路径长度比较循环、卷积与 self-attention。Self-attention 缩短远距离依赖路径并允许训练时并行处理序列，却需构造随序列长度平方增长的相关性矩阵。短到中等序列时优势明显；长上下文中则需要稀疏、分块、滑窗或 I/O-aware kernel 等优化，而且这些方法各自改变计算、可见范围或数据移动，不能混称为同一种加速。" },
    { title: "从公式到实现要检查 mask、位置与数值稳定性", body: "实现错误常藏在广播后的 mask 方向、padding 与 causal mask 的组合、位置编号偏移、softmax 前的 dtype 和多头 reshape 顺序。建立小矩阵金向量：固定 Q/K/V，保存缩放前后分数、mask 后分数、softmax 权重与最终输出；检查每行权重和为 1，未来位置权重为 0。这样后续优化 kernel、量化或 KV cache 时，能够定位第一个破坏语义的边界。" },
  ]),
  pitfall: "把 Attention 当成“自动理解重点”的解释器，或把训练阶段的并行性误读成生成阶段没有依赖。Attention 是可学习的加权数据流，其行为由权重、位置、mask 与输入共同决定，并仍承担 O(n²) 的长序列代价。",
  references: [["《Attention Is All You Need》原始论文", "https://arxiv.org/abs/1706.03762"], ["BERT 原始论文", "https://arxiv.org/abs/1810.04805"], ["FlashAttention 原始论文", "https://arxiv.org/abs/2205.14135"]],
  quiz: [
    old[9].quiz[0],
    { prompt: "Causal mask 在 decoder self-attention 中保证什么？", options: ["所有 head 共享参数", "当前位置不能读取未来 token", "序列长度固定为 512", "自动删除 padding token"], answer: 1, explanation: "Causal mask 把未来位置设为不可见，使训练时并行计算仍遵守自回归语义。" },
    { prompt: "序列长度翻倍时，完整 attention score 矩阵的元素数约如何变化？", options: ["保持不变", "约变为四倍", "约变为两倍", "约减半"], answer: 1, explanation: "score 矩阵通常是 n×n；序列从 n 变成 2n 时，元素数从 n² 变成 4n²。" },
  ],
  readingMinutes: 20,
  keywords: [
    { term: "Attention", definition: "用 Query 与 Key 的匹配分数对 Value 加权聚合的信息交换机制。", espAnalogy: "像按当前查询同时检索多个带索引的 DMA 描述符。" },
    { term: "Multi-head", definition: "把表示投影到多个子空间并行执行注意力，再拼接输出。", espAnalogy: "像并行运行多组过滤规则，各自观察不同协议特征。" },
    { term: "Causal mask", definition: "阻止当前位置访问未来 token 的上三角可见性约束。", espAnalogy: "像接收状态机只能读取已经到达的字节。" },
    { term: "Positional encoding", definition: "向无循环的注意力网络注入 token 顺序或相对距离信息。", espAnalogy: "像给每个环形缓冲区元素附带单调序号。" },
  ],
  recap: "上一章先建立了完整 Transformer 架构，明确 Attention 只是 block 中负责跨位置通信的子层。本章把这个大概念单独展开，追踪 Q、K、V、mask、多头和位置如何共同决定信息聚合。",
  nextPreview: "下一章只讨论 KV Cache：旧 token 的 K/V 为什么可复用、每新增 token 需要多少内存，以及 GQA、分页和量化如何改变容量与带宽。",
  history: {
    intro: "Attention 从改善 encoder–decoder 对长句的压缩瓶颈开始，随后成为 Transformer 的核心数据流，并扩展到双向预训练、跨模态与 I/O-aware kernel。结构创新与系统优化共同决定它今天能处理多长的上下文。",
    milestones: [
      { year: "2014", title: "可学习对齐缓解固定长度编码瓶颈", body: "Bahdanau 等人在神经机器翻译中让 decoder 每一步对 encoder 状态计算对齐权重，不再要求一个固定向量承载整句信息。", source: { label: "神经机器翻译 Attention 原始论文", url: "https://arxiv.org/abs/1409.0473" } },
      { year: "2017", title: "Transformer 以多头 Attention 取代循环主干", body: "缩放点积、多头 self-attention、位置编码和 causal mask 被组织成可并行训练的 encoder–decoder 架构。", source: { label: "Transformer 原始论文", url: "https://arxiv.org/abs/1706.03762" } },
      { year: "2018", title: "BERT 用双向 self-attention 建立通用语言表示", body: "Masked language modeling 让表示同时利用左右上下文，展示 Transformer encoder 预训练迁移到多类理解任务的能力。", source: { label: "BERT 原始论文", url: "https://arxiv.org/abs/1810.04805" } },
      { year: "2019", title: "Transformer-XL 引入跨片段记忆与相对位置", body: "跨 segment 复用隐藏状态并采用相对位置编码，使语言模型能够处理比固定训练片段更长的依赖。", source: { label: "Transformer-XL 原始论文", url: "https://arxiv.org/abs/1901.02860" } },
      { year: "2020", title: "Vision Transformer 把纯 Transformer 主干带到图像", body: "图像被切成 patch 序列后直接进入 Transformer，说明 attention 的位置交互机制并不局限于自然语言。", source: { label: "Vision Transformer 原始论文", url: "https://arxiv.org/abs/2010.11929" } },
      { year: "2022", title: "FlashAttention 把瓶颈定位到 HBM 数据移动", body: "I/O-aware 分块在不近似 attention 结果的前提下减少 HBM 读写，表明相同数学公式可因内存层级调度产生巨大实现差异。", source: { label: "FlashAttention 原始论文", url: "https://arxiv.org/abs/2205.14135" } },
    ],
    bridge: "端侧实现既要保留 Q/K/V、mask 和位置语义，也要面对序列平方计算与内存层级。先建立小矩阵正确性基线，再选择融合、分块、低精度或硬件 backend。",
  },
  visual: {
    title: "一个 token 如何通过多头 Self-Attention 读取上下文",
    description: "播放器沿张量路径展示投影、打分、屏蔽、归一化、聚合与输出，而不是把 Attention 隐藏在一个黑盒节点里。",
    steps: [
      { icon: "🔢", label: "嵌入位置", data: "X = token embedding + position", action: "为每个位置建立带顺序的表示", insight: "Attention 本身不会自动产生顺序" },
      { icon: "🔀", label: "投影 Q/K/V", data: "XWq, XWk, XWv", action: "按 head 重排到多个表示子空间", insight: "同一输入承担查询、索引和值三种角色" },
      { icon: "📐", label: "计算缩放分数", data: "QKᵀ / √dₖ", action: "计算每个查询与所有 key 的匹配", insight: "缩放防止大维点积让 softmax 饱和" },
      { icon: "🚧", label: "应用可见性", data: "scores + causal/padding mask", action: "屏蔽未来位置和无效 padding", insight: "mask 是模型语义，不只是优化提示" },
      { icon: "⚖️", label: "归一化并读取 V", data: "softmax(scores) @ V", action: "把可见 value 加权汇总", insight: "每行权重应形成概率分布" },
      { icon: "🧩", label: "拼接并进入 block", data: "concat(heads)Wₒ → residual → FFN", action: "合并多头信息并继续非线性变换", insight: "Attention 只是完整 Transformer block 的一部分" },
    ],
    loop: "每个 Transformer block 都重复这条路径；训练时多个位置可并行，生成时新的位置仍必须等待上一 token 被选择。",
  },
  analogyDetail: {
    title: "一座并行检索、分频道汇总的交换矩阵",
    story: "每个输入端口发出查询，多套匹配电路分别按语法、位置或语义线索给可见端口打分，再从对应数据通道读取内容。各频道结果拼接后进入本地处理单元。矩阵可以同时服务整批输入，但如果下一个输入本身尚未产生，就不能提前处理。",
    illustration: [
      { icon: "❓", label: "查询描述符", mapsTo: "Query：当前位置想寻找什么" },
      { icon: "🏷️", label: "端口索引", mapsTo: "Key：每个位置如何被匹配" },
      { icon: "📦", label: "端口数据", mapsTo: "Value：匹配后实际取回的信息" },
      { icon: "📡", label: "多组匹配频道", mapsTo: "多个 attention head 的并行子空间" },
    ],
    boundary: "权重不是人类可直接命名的“语法头”或“事实头”，attention score 也不能单独证明模型的因果解释；类比只描述数据流与并行结构。",
  },
});

const day11 = revise(old[9], 11, {
  t: "KV Cache",
  s: "用会话内存换取 Decode 阶段的历史投影复用",
  goal: "理解 Prefill 与 Decode 的工作负载差异、K/V 为什么可缓存、cache 张量布局和容量斜率，并能比较 MHA、GQA、MQA、分页与低精度策略。",
  concept: ["Prefill 与 autoregressive Decode", "K/V 可复用的数学前提", "cache shape、生命周期与位置", "GQA/MQA 与低精度 KV", "paged KV、滑窗、复用与回收"],
  analogy: "像为已经解析的历史报文保存分层索引：新字段不必重做旧字段的索引构建，但仍要扫描可见索引并为新增字段分配状态。",
  diagram: "Prompt tokens ──Prefill──► per-layer K/V cache\nNew token ──Q,K,V──► Q × cached Kᵀ → weighted V → logits → sample\n                         └──── append new K/V and repeat ────┘",
  code: "kv_bytes = batch * layers * 2 * tokens * kv_heads * head_dim * bytes_per_value\nbytes_per_new_token = batch * layers * 2 * kv_heads * head_dim * bytes_per_value\n# 实现还需计入对齐、分页元数据与预分配策略",
  lab: "为一个实际模型读取 layers、kv_heads、head_dim 与 cache dtype，先手算每新增 token 的 KV 字节数，再分别估算 512、2048、4096 token。运行本地 runtime 改变 context 长度，记录内存、prefill 时间与每 token 延迟；若支持 GQA/MQA 或 KV 量化，再比较容量斜率和输出质量。",
  questions: ["为什么旧 token 的 K/V 可以复用而 Q 通常不长期保存？", "KV cache 容量为何通常随 context 近似线性增长？", "分页、GQA 与滑窗分别解决什么问题？"],
  next: "LLM 量化与 GGUF",
  lesson: old[9].lesson.slice(4).concat([
    { title: "Prefill 与 Decode 必须分开记账", body: "Prefill 批量处理 prompt 的全部 token，通常有更高并行度和计算密度；Decode 每轮只产生一个新位置，却反复读取逐渐增长的历史 K/V，常更受内存带宽和调度开销影响。TTFT 包含排队、tokenize、prefill 与首轮采样，ITL 则关注后续 token 间隔。把两者平均成一个 tokens/s，会掩盖长 prompt、短回答和多会话场景中完全不同的瓶颈。" },
    { title: "Cache 正确性依赖模型、前缀、位置和精度", body: "K/V 是特定层权重、特定 token 前缀、位置编码和 cache dtype 下产生的中间张量。模型或 adapter 改变、前缀中间被编辑、position 偏移或旋转位置参数不一致时，旧 cache 通常不可直接复用。Prompt cache 的键必须覆盖这些身份信息；取消、超时和会话淘汰还要把页面或槽位完整归还，否则系统会在长时间运行后出现隐性容量泄漏。" },
  ]),
  pitfall: "只按权重文件估算 RAM，或把分页、滑窗与 GQA 都称为“压缩 KV”。它们分别处理碎片、可见历史和每 token 状态宽度，容量、语义和质量代价不同。",
  references: [["GQA 原始论文", "https://arxiv.org/abs/2305.13245"], ["vLLM / PagedAttention 原始论文", "https://arxiv.org/abs/2309.06180"], ["KIVI KV Cache 量化原始论文", "https://arxiv.org/abs/2402.02750"]],
  quiz: old[9].quiz.slice(1).concat([{ prompt: "PagedAttention 主要直接改善什么？", options: ["把参数永久写入 tokenizer", "动态会话 KV 的分配、碎片与共享", "消除自回归顺序", "保证回答事实正确"], answer: 1, explanation: "分页把逻辑连续的会话状态映射到非连续物理块，主要改善动态增长 KV 的内存管理。" }]),
  readingMinutes: 19,
  keywords: [
    { term: "Prefill", definition: "批量处理已有 prompt 并为每层建立初始 K/V 状态的阶段。", espAnalogy: "像连接建立时一次性解析完整握手报文。" },
    { term: "Decode", definition: "根据上一步输出逐 token 追加位置并生成下一 token 的阶段。", espAnalogy: "像事件循环每轮等待上一步结果后再推进状态机。" },
    { term: "KV cache", definition: "保存历史 token 在每层产生的 Key 与 Value 投影的会话状态。", espAnalogy: "像按层保存已核验字段的索引与数据描述符。" },
    { term: "GQA / MQA", definition: "让多组 Query head 共享更少 K/V head，从结构上降低每 token cache 宽度。", espAnalogy: "像多个消费者共享较少的只读索引表。" },
  ],
  recap: "上一章把 Attention 的 Q/K/V、causal mask 与多头聚合拆成显式数据流。本章只研究生成阶段如何复用历史 K/V，以及这种复用产生的会话内存、带宽与回收责任。",
  nextPreview: "下一章进入 LLM 量化与 GGUF：把权重、张量类型、block 开销、metadata 与输出质量连成可验证的模型包。",
});

const course = [
  revise(old[0], 1, { t: "神经网络基础", s: "从张量、层与损失函数建立神经网络直觉", next: "训练与推理", nextPreview: "下一章把训练态、推理态、计算图、权重与格式契约连成一条可验证的模型交付链。" }),
  revise(old[1], 2, {
    t: "训练与推理",
    s: "把可学习状态冻结为可移植、可验证的模型产物",
    goal: "理解训练态与推理态的差异，并能把 checkpoint 转换为包含计算图、权重、版本和预处理契约的部署产物。",
    concept: ["训练循环与优化器状态", "train/eval 运行语义", "计算图、权重与 metadata", "IR、opset 与 runtime 兼容", "导出、转换与分层等价验证"],
    analogy: "像把可调试的协议栈工程冻结成发布固件：训练日志与调试状态留在实验室，设备只接收固定执行路径、常量、版本和 I/O 契约。",
    diagram: "data + labels → train state → checkpoint\n                              │ eval/freeze/export\n                              ▼\ninput contract → graph + weights + metadata → runtime/backend",
    code: "model.eval()\nexport(model, example_input, opset_version=...)\nassert_close(reference_output, runtime_output)\n# 同时保存 tokenizer/labels/preprocess/version",
    lab: "训练一个小模型并保存 checkpoint；切换 eval 后导出 ONNX 或 LiteRT，列出图、权重、opset、输入 shape/dtype 和前处理版本。用三组金输入比较框架、导出图与目标 runtime 的中间或最终输出。",
    questions: [old[1].questions[1], old[2].questions[0], old[2].questions[2]],
    next: "模型量化",
    lesson: [old[1].lesson[0], old[1].lesson[1], old[1].lesson[2], old[2].lesson[0], old[2].lesson[2], old[2].lesson[3], old[2].lesson[4]],
    pitfall: "只保存权重文件，或看到转换成功就认为语义一致。部署产物还依赖图版本、算子集、前后处理、标签与 runtime；每次变换都必须通过金向量验证。",
    references: [old[1].references[0], old[2].references[0], old[2].references[2]],
    quiz: [old[1].quiz[0], old[2].quiz[0], old[2].quiz[2]],
    readingMinutes: 20,
    keywords: [old[1].keywords[2], old[1].keywords[3], old[2].keywords[0], old[2].keywords[1]],
    recap: "上一章解释了张量、梯度和一次权重更新；本章追踪这些训练状态如何被冻结、转换并交付给不执行反向传播的设备 runtime。",
    nextPreview: "下一章研究量化：在明确模型 ABI 后，用校准与误差证据把浮点表示映射到低比特整数。",
    history: { intro: "模型交付链由训练算法、运行模式、图表示与互操作标准共同形成。它把“一个实验能复现”推进为“一个产物能在另一套 runtime 上保持语义”。", milestones: [old[1].history.milestones[0], old[1].history.milestones[2], old[1].history.milestones[4], old[2].history.milestones[0], old[2].history.milestones[2], old[2].history.milestones[4]], bridge: "今天应把 checkpoint、导出图、权重、metadata 与前后处理作为一个版本化模型包，并沿转换链逐层比较输出。" },
    visual: old[2].visual,
    analogyDetail: old[1].analogyDetail,
  }),
  revise(old[3], 3, { t: "模型量化", s: "用更少的 bit 换取更低的存储与带宽", next: "算子与 Kernel", recap: "上一章建立了从训练状态到模型包的交付契约；本章开始改变数值表示，用可测误差换取存储、带宽和 kernel 机会。", nextPreview: "下一章沿算子契约进入 layout、tiling、fusion 与硬件 kernel。" }),
  revise(old[4], 4, { t: "算子与 Kernel", s: "从数学定义走到布局、融合与硬件执行路径", next: "端侧模型部署", recap: "上一章把浮点值映射到低比特表示；本章追踪这些值如何被算子、布局与 kernel 真正执行。", nextPreview: "下一章把数据、训练、转换、量化与固件 runtime 串成非 LLM 端侧部署闭环。" }),
  revise(old[5], 5, { t: "端侧模型部署", s: "把非 LLM 视觉、音频与传感器模型真正烧进设备", next: "端侧视觉流水线", recap: "前四章已经建立模型数学、产物契约、量化与 kernel 基础；本章把它们放进真实 TinyML 项目的训练—转换—固件闭环。", nextPreview: "下一章合并资源预算与视觉流水线，在 Flash、SRAM、PSRAM、DMA、前处理和事件后处理之间完成稳态验收。" }),
  revise(old[6], 6, {
    t: "端侧视觉流水线",
    s: "在内存、带宽与实时约束中把摄像头帧变成稳定事件",
    goal: "能够为 MCU/NPU 视觉系统计算峰值内存和带宽，定义 frame buffer、几何变换、后处理与所有权契约，并用稳态证据验收。",
    concept: ["Flash、SRAM、PSRAM 与峰值活跃内存", "DMA、stride、layout 与 buffer ownership", "分类、检测、分割与 ROI/letterbox", "NPU partition、fallback 与数据搬运", "NMS、时序平滑、能耗与热稳态"],
    analogy: "像一条空间有限的实时视频管线：仓库容量、传送带带宽、托盘所有权、工位节拍和最终质检必须一起设计。",
    diagram: "camera DMA → frame buffer → ROI/resize/letterbox → model partition\n       ▲ ownership/stride      SRAM↔PSRAM↔NPU         │\n       └──────── release ◄── NMS + temporal policy ◄──┘",
    code: "frame = camera_acquire()\ninput, transform = preprocess(frame)\nraw = infer(input)\nevent = postprocess(raw, transform)\ncamera_release(frame)\nassert peak_live_bytes <= memory_budget",
    lab: "选择一块 ESP32 摄像头板，列出 frame buffer、模型权重、tensor arena、临时 resize buffer 和输出的生命周期；计算峰值而非总和。回放一张带目标图片，保存原图、letterbox 后输入、raw output 和 NMS 结果，并验证框坐标可逆映射。连续运行 10 分钟记录 FPS、内存低水位、温度或功耗。",
    questions: [old[6].questions[0], old[7].questions[0], old[7].questions[1]],
    next: "LLM 基础",
    lesson: [old[6].lesson[0], old[6].lesson[1], old[6].lesson[2], old[7].lesson[0], old[7].lesson[1], old[7].lesson[2], old[7].lesson[4]],
    pitfall: "把模型文件大小当峰值 RAM，或在 frame buffer 仍被 DMA/驱动持有时原地改写。资源预算必须按生命周期重叠计算，图像变换必须保存 stride、所有权和可逆几何信息。",
    references: [old[6].references[0], old[7].references[0], old[7].references[2]],
    quiz: [old[6].quiz[0], old[7].quiz[0], old[7].quiz[1]],
    readingMinutes: 20,
    keywords: [old[6].keywords[0], old[6].keywords[2], old[7].keywords[0], old[7].keywords[1]],
    recap: "Day 5 已把非 LLM 模型部署到 MCU；本章把资源账本与摄像头数据链合并，回答它能否在真实帧率、内存和热状态下长期稳定工作。",
    nextPreview: "下一章是课程分界点：从传统判别式端侧模型进入 LLM，建立语言模型发展脉络、核心术语和能力边界。",
    history: { intro: "端侧视觉能力来自轻量网络、内存层级、DMA 与完整前后处理共同演进。峰值算力只有在数据能及时到达、buffer 生命周期正确且输出可还原时才有意义。", milestones: [old[6].history.milestones[1], old[6].history.milestones[2], old[6].history.milestones[4], old[7].history.milestones[1], old[7].history.milestones[2], old[7].history.milestones[4]], bridge: "今天应把一帧的每次格式、几何、所有权和存储层级变化写进同一条 trace，并在持续运行中观察内存低水位与时序稳定性。" },
    visual: old[7].visual,
    analogyDetail: old[6].analogyDetail,
  }),
  day7,
  revise(old[8], 8, { next: "Transformer 架构", recap: "上一章建立了 LLM 的概率目标、发展脉络与状态术语；本章从输入端开始，固定字符、字节、token、特殊标记和消息模板的精确契约。", nextPreview: "下一章把 Transformer 作为完整架构单独展开，先建立 token、位置、block、FFN、残差、归一化与 logits 的全局路径。" }),
  day9,
  day10,
  day11,
  revise(old[11], 12, { t: "LLM 量化与 GGUF", s: "把低比特权重与 metadata 封装成可部署模型包", next: "LLM Runtime", recap: "上一章已经为逐 token 增长的 KV 状态建立容量账本；本章进一步压缩跨请求复用的权重，并把 GGUF metadata 视为可验证的模型包契约。", nextPreview: "下一章把模型包真正交给 runtime 和端侧推理框架，检查加载、采样、调度、backend 分区、fallback 与取消路径。" }),
  revise(old[10], 13, {
    t: "LLM Runtime",
    s: "把模型包、生成循环与异构 backend 组织成可观测执行路径",
    goal: "理解 runtime 如何加载模型、管理会话、调度 Prefill/Decode、执行采样与流式取消，并能用分层验收矩阵比较 CPU、GPU、NPU backend、编译方式、子图分区和 fallback。",
    concept: ["模型加载、mmap 与进程资源", "Prefill/Decode、采样、流式与取消", "Runtime、图编译器、backend 与硬件层", "CPU/GPU/NPU 分区和边界复制", "Fallback、可观测性与框架验收"],
    analogy: "像一座带多条生产线的调度车间：runtime 接单、维护在制品并决定节拍，编译器生成工艺路线，各 backend 执行自己支持的工序；跨线搬运和返工必须被记录。",
    diagram: "model package → loader/compiler → runtime request loop\n                                  │\n       CPU baseline ↔ GPU delegate ↔ NPU partition\n queue → prefill → decode → sample → stream / cancel / reclaim",
    code: "engine = load(model_package, backend_policy)\nfor request in scheduler:\n    state = prefill(request.tokens)\n    while not request.done:\n        logits, state = decode_one(state)\n        request.stream(sampler(logits))\n    reclaim(state)  # cancel/error 也走同一释放路径",
    lab: "选择一个本地 LLM 和两个可用执行配置。固定模型、GGUF、prompt、线程、context 与输出长度，先建立 CPU 正确性基线，再开启 GPU/NPU delegate 或 offload。记录模型加载时间、TTFT、ITL、峰值 RSS、实际算子/层分区、边界复制、fallback 和取消后的资源回收；用相同金提示比较输出 token 与日志，形成一页框架验收矩阵。",
    questions: [old[10].questions[0], old[12].questions[0], old[12].questions[2]],
    next: "LLM 性能与 Infra",
    lesson: [old[10].lesson[0], old[10].lesson[2], old[10].lesson[3], old[12].lesson[0], old[12].lesson[1], old[12].lesson[2], old[12].lesson[4]],
    pitfall: "把能加载模型当成框架适配完成，或只比较品牌与峰值 tokens/s。必须证明 tokenizer/模板一致、算子实际落到目标 backend、边界复制可解释、fallback 可见，且取消与异常能完整回收会话状态。",
    references: [["llama.cpp 官方仓库", "https://github.com/ggml-org/llama.cpp"], old[12].references[0], old[12].references[1]],
    quiz: [old[10].quiz[0], old[12].quiz[0], old[12].quiz[2]],
    readingMinutes: 20,
    keywords: [old[10].keywords[0], old[10].keywords[3], old[12].keywords[0], old[12].keywords[1]],
    recap: "前六天建立传统端侧模型执行链，Day 7–12 又补齐 LLM 的输入、架构、Attention、KV 与模型包。本章把这些静态契约放进真实 runtime，请求调度与异构 backend 从此成为一条可追踪的数据和控制路径。",
    nextPreview: "下一章从单机 benchmark 扩展到芯片、互连、并行训练、在线服务与 SLO，建立跨尺度性能证据。",
    history: {
      intro: "LLM runtime 与端侧框架共同承接模型语义和硬件现实：前者管理生成状态与请求生命周期，后者通过图变换、编译和 delegate 把算子映射到异构设备。两条历史最终汇合为一条必须可观测、可回退的执行路径。",
      milestones: [old[10].history.milestones[0], old[10].history.milestones[2], old[10].history.milestones[4], old[12].history.milestones[0], old[12].history.milestones[2], old[12].history.milestones[4]],
      bridge: "先用 CPU 与金输入固定语义，再逐层打开量化模型包、编译变换、子图分区和硬件 delegate；每增加一层优化，都要留下实际执行节点、复制边界、版本和 fallback 证据。",
    },
    visual: old[12].visual,
    analogyDetail: old[10].analogyDetail,
  }),
  revise(old[15], 14, {
    t: "LLM 性能与 Infra",
    s: "从单机 TTFT/ITL 追到集群数据移动、并行拓扑与 SLO",
    goal: "用可复现实验定位单机推理瓶颈，并理解训练并行、KV 调度、Prefill/Decode 解耦与服务 SLO 如何把同一资源账本扩展到集群。",
    concept: ["TTFT、ITL、吞吐与分位数", "Roofline、带宽、能耗与热稳态", "DP/TP/PP/CP/EP 与通信拓扑", "KV、continuous batching 与 PD 解耦", "训练 goodput、推理 SLO 与故障恢复"],
    analogy: "像从一趟列车晚点追到整张铁路网：先固定单车时刻与载荷，再分析站内换乘、干线带宽、调度策略和准点率目标。",
    diagram: "request → queue → prefill → decode → stream\n             │ TTFT      │ ITL / KV\nchip memory ↔ scale-up ↔ scale-out ↔ storage\n             └── topology + parallelism + SLO ──┘",
    code: "record(model, quant, prompt_tokens, output_tokens, hardware, temperature)\nmeasure(TTFT, ITL_p50, ITL_p95, tokens_per_s, joules_per_token)\n# 集群侧再记录 collective、KV 占用、goodput 与失败恢复时间",
    lab: "固定模型、量化、prompt 与输出长度，完成冷启动和预热后的 10 次本地基准，记录 TTFT、ITL p50/p95、RSS、功耗和温度。然后把一次请求画到“芯片内存→scale-up→scale-out→存储”层级，分别标出若采用 TP、PP、分片训练或 PD 解耦会新增的通信，并写出它可能改善和恶化的指标。",
    questions: [old[13].questions[0], old[15].questions[1], old[15].questions[2]],
    next: "端侧 LLM 产品化",
    lesson: [old[13].lesson[0], old[13].lesson[1], old[13].lesson[2], old[15].lesson[0], old[15].lesson[1], old[15].lesson[3], old[15].lesson[6]],
    pitfall: "只报告峰值 tokens/s，或把某个并行/解耦策略当成普适加速。任何结果都必须绑定模型、精度、序列、并发、硬件拓扑、热状态和 SLO；边界通信可能吞掉局部收益。",
    references: [old[13].references[0], old[15].references[0], old[15].references[2]],
    quiz: [old[13].quiz[0], old[15].quiz[1], old[15].quiz[2]],
    readingMinutes: 20,
    keywords: [old[13].keywords[0], old[13].keywords[1], old[15].keywords[0], old[15].keywords[3]],
    recap: "Day 13 已能证明请求实际经过哪些 backend；本章把正确性基线升级为跨尺度性能账本，从单设备测量延伸到集群通信、状态调度和服务目标。",
    nextPreview: "终章把模型包、runtime、异构 backend、MCU/Host 安全边界、能耗、回退、OTA 与可观测性收束成可交付的端侧 LLM 产品。",
    analogyDetail: old[13].analogyDetail,
  }),
  revise(old[16], 15, {
    t: "端侧 LLM 产品化",
    s: "把模型、异构硬件、MCU/Host 边界与运营证据收束为可交付系统",
    goal: "完成端侧 LLM 的三级职责边界、模型包契约、异构执行、容量与能耗预算、故障降级、版本发布和验收报告。",
    concept: ["MCU、Edge Host 与云端三级职责", "模型包、tokenizer、runtime 与 backend 契约", "权重、激活、KV、workspace 与峰值 RSS", "工具调用安全边界、显式回退与降级", "质量、体验、能耗、热状态、OTA 与可观测性"],
    analogy: "像把云端厨房装进一辆受限餐车：菜单、设备、储物、能源、卫生规则和应急路线必须作为一个系统验收。",
    diagram: "sensor/actuator ↔ MCU deterministic gate ↔ Edge Host LLM\n                         │ validate tool proposal │\n                         └── explicit cloud fallback\nmodel package → runtime/backend → telemetry → staged OTA/rollback",
    code: "proposal = edge_llm(request)\nvalidated = policy_and_schema_check(proposal)\nif validated:\n    mcu_execute(validated)\nelse:\n    enter_safe_degraded_state()\nrecord(version_set, latency, energy, thermal, failures)",
    lab: "为一个 ESP32 + Edge Host 项目写一页验收契约：明确模型只可提出哪些动作、MCU 如何验证；固定模型、tokenizer、模板、runtime、backend、固件和协议版本；计算权重、KV、workspace、I/O 与峰值 RSS；连续运行并记录 TTFT、ITL、能耗、热稳态和失败。最后演练主机离线、模型加载失败、超时、非法工具参数与 OTA 回滚。",
    questions: [old[14].questions[0], old[16].questions[0], old[16].questions[1]],
    next: null,
    lesson: [old[14].lesson[0], old[14].lesson[1], old[14].lesson[2], old[16].lesson[1], old[16].lesson[2], old[16].lesson[3], old[16].lesson[6]],
    pitfall: "让自然语言输出直接获得设备执行权，或只验证一次演示。可交付系统必须在确定性边界内校验动作，并以版本化、稳态、故障演练和可回滚证据完成验收。",
    references: [old[14].references[1], old[16].references[0], old[16].references[2]],
    quiz: [old[14].quiz[0], old[16].quiz[0], old[16].quiz[1]],
    readingMinutes: 20,
    keywords: [old[14].keywords[0], old[16].keywords[0], old[16].keywords[1], old[16].keywords[3]],
    recap: "前十四天已从神经网络基础走到 LLM 结构、运行时、量化、框架和跨尺度性能。本章把全部知识压回一个真实产品：谁有执行权、每个字节和每焦耳花在哪里、失败时如何保持安全、版本如何发布与回滚。",
    nextPreview: "15 天路线已经完成。下一次项目从目标设备和真实工作负载开始：先写安全与验收边界，再选择模型与 runtime，并让每次优化都留下可复现证据。",
  }),
];

module.exports = course;
